### ISSUE TITLE
今后的版本发布就在这里好吗？

### ISSUE THREAD

**Issue by 775405984** [wmjordan/PDFPatcher#1]
不如今后将版本发布在这里，用户既可以通过rss订阅及时获得最新版本，也不必再忍受诚通网盘的龟速下载。

谢谢！

**Comment by wmjordan** [comment]
这里联网不稳定。上传大一点儿的文件就不行了。

**Comment by mini1025** [comment]
可以用兰奏

**Comment by duanluan** [comment]
> 不如今后将版本发布在这里，用户既可以通过 rss 订阅及时获得最新版本，也不必再忍受诚通网盘的龟速下载。
> 
> 谢谢！

作者用城通网盘还能赚点小钱呢，就多下载一会儿，其实你可以用那种制作 rss 的工具把城通网盘的页面制作成订阅，我看地址也一直没变过，不过本来打开软件的时候就会检测更新啊

**Comment by wmjordan** [comment]
日前收到用户留言，说城通网盘现在要下载客户端才能下载文件。这实在让人感到麻烦。
刚才已更换了网盘，暂改到蓝奏云盘。

**Comment by wmjordan** [comment]
> 可以考虑在Gitee建立一个镜像。以这个项目的高价值，详细很快加星数量会破百，那么就可以向Gitee申请"年度最有价值项目"，通过后，将能免费使用Gitee的一些原本收费的资源，比如源码深度分析服务。

嗯，会考虑迁到码云的

**Comment by wmjordan** [comment]
鉴于这个网站访问不太稳定，我在码云上也创建了代码仓库。
然而，我发现码云创建问题时似乎不能选择问题种类，也不能轻松地粘贴上传剪贴板的截图，还不能上传附件，似乎不太方便。

**Comment by calcitem** [comment]
因政策问题，GitHub后续的稳定性问题只会越来越大，因此在码云做个镜像作为备份可以是以防万一，可以公告提示提问题请移步GitHub。目前人气还是GitHub旺。此外在码云有个镜像的话，可以使用码云提供的一些特色服务。

**Comment by meetpython** [comment]
请问未来是否会有 MacOS 或 Linux 的版本？

**Comment by calcitem** [comment]
> 请问未来是否会有 MacOS 或 Linux 的版本？

See https://github.com/wmjordan/PDFPatcher/issues/20

**Comment by meetpython** [comment]
> > 请问未来是否会有 MacOS 或 Linux 的版本？
> 
> See
> 
> #20
> 
> #26

已了解。请问 GitHub 上何时会有 1.0 版本的稳定版的 Windows 的下载？

**Comment by calcitem** [comment]
稳定版是在蓝奏网盘下载的哦

**Comment by wmjordan** [comment]
稳定版是0.6.2。
一般来说，建议还是下载最新的。

**Comment by meetpython** [comment]
> 稳定版是在蓝奏网盘下载的哦

谢谢，能否提供一个网盘的地址？的确没找到从哪里下载。麻烦了。

**Comment by calcitem** [comment]
百度 pdf补丁丁 k14s

**Comment by wmjordan** [comment]
我用各位网友在城通网盘下载产生的收益，赊账购买了城通网盘的终身超级会员。
目前发布了新的版本 3867，下载连接应已直连加速，无需再打开下载页面。
在“帮助”菜单“检查新版本”处即可下载。我刚才测试了一下，几秒钟内就能下完。

**Comment by wmjordan** [comment]
@zhongfly 
感谢提醒，有更新的测试版了，已修复该连接。
