### ISSUE TITLE
Visual Studio 2019 Compile Error

### ISSUE THREAD

**Issue by brantxiong** [wmjordan/PDFPatcher#10]
Error Logs:

```log
已启动生成…
1>------ 已启动生成: 项目: PDFPatcher, 配置: Debug x86 ------
1>CSC : error CS7027: 使用来自文件“wmjordan.snk”的公钥对输出签名时出错 -- 未找到文件。
========== 生成: 成功 0 个，失败 1 个，最新 1 个，跳过 0 个 ==========
```

**Comment by calcitem** [comment]
您可以参考下我上午刚close的PR。

**Comment by brantxiong** [comment]
多谢，修改 `PDFPatcher\App\PDFPatcher.csproj` 之后，`Debug`版本编译运行通过了，但 `Release`版本还是编译报错：
```log
2>  Added assembly '..\bin\Release\PDFPatcher.exe'
2>  Added assembly '..\bin\Release\ColorPicker.dll'
2>  Added assembly '..\bin\Release\Cyotek.Windows.Forms.ImageBox.dll'
2>  Added assembly '..\bin\Release\FreeImageNET.dll'
2>  Added assembly '..\bin\Release\HtmlRenderer.dll'
2>  Added assembly '..\bin\Release\HtmlRenderer.WinForms.dll'
2>PDFPatcher\App\ILRepack.targets(19,3): error : Unable to resolve assembly '..\bin\Release\itextAsian.dll'
```

**Comment by brantxiong** [comment]
补充，`Debug`版本运行报错：

![image](https://user-images.githubusercontent.com/3325773/148032181-60394b4e-a2d6-43d1-a277-c68e599ae786.png)

**Comment by wmjordan** [comment]
在开源代码的时候，csproj 可能漏了引用 itextasian。

等我有空看看是不是这样。

**Comment by TroyDanielFZ** [comment]
之前我编译成功过，记得主要操作用两点。
1. 添加App\Lib\下的所有dll的引用
2. 把csproj(或者是另外一个文件）里面含有"wmjordan.snk"的一行删除（或者是在项目设置里勾选不加密，具体哪一个忘记了）。

**Comment by calcitem** [comment]
> 之前我编译成功过，记得主要操作用两点。
> 
> 1. 添加App\Lib\下的所有dll的引用
> 2. 把csproj(或者是另外一个文件）里面含有"wmjordan.snk"的一行删除（或者是在项目设置里勾选不加密，具体哪一个忘记了）。

感谢分享，刚也遇到了此问题。是不是干脆顺手Push个PR上来？

我觉得创始人的主要精力可以腾挪到更重要的事情上，这些杂货我们顺手搞定就行。

**Comment by wmjordan** [comment]
请重新拉取代码，现在应该可以顺利编译 Debug 版本了。
Release 版本少了文件，也是无法正常编译的。发布脚本不能正常执行。
请暂时也不要提交“修复 Release 版本编译问题”的拉取请求。
