### ISSUE TITLE
无法导出文本书签，即使选择了txt格式，导出的文件仍然是xml格式

### ISSUE THREAD

**Issue by ShengYULAN** [wmjordan/PDFPatcher#100]
**请简要描述你遇到的问题**
无法导出文本书签，即使选择了txt格式，导出的文件仍然是xml格式
**重现问题的步骤**
步骤如下：
1. 使用如下附件 '...'
2. 打开某功能 '....'
3. 选中哪些选项，点击哪些按钮 '....'
4. 出现的问题

**预期的结果或行为**
在完成上面的操作步骤后，您觉得程序应该是怎样工作的。

**相关截图或文件**
如果有必要，请附上截图或文件（最好能附上程序的界面截图，以便了解你现在使用的版本和操作选项等）

**其它**
与本问题相关的信息
![动画](https://user-images.githubusercontent.com/75264521/166861844-611aabd7-a249-45a2-935a-5c45d8fd6769.gif)

**Comment by wmjordan** [comment]
请到 #2 下载新的测试版

**Comment by ShengYULAN** [comment]
bug已经修复,不过输出文件不是我想要的效果.
输出的文件包含大量的字体信息,而且很多不相关的信息,但是我只想要书签信息.
而且我发现只要字体大于你设定的最低标准,都会输出,但是我只想要某些特定的标题输出.
请问这个软件能不能实现"*指定页面范围内的自动生成书签"的功能*?
你的软件可以先设置标题的级别,然后生成书签,但是这个功能在全部页面范围生效,我希望这个功能能够在选定页面范围内生效.
附件为对比图

WMJ ***@***.***> 于2022年5月5日周四 14:56写道：

**Comment by wmjordan** [comment]
> 我只想要书签信息

请试试增加筛选条件

**Comment by wmjordan** [comment]
> 请问这个软件能不能实现"*指定页面范围内的自动生成书签"的功能*? 你的软件可以先设置标题的级别,然后生成书签,但是这个功能在全部页面范围生效,我希望这个功能能够在选定页面范围内生效.

请介绍一下在特定页面范围内生效的具体场景，最好能展示一下文档
