### ISSUE TITLE
替换字体功能，替换字体列表内找不到部分已安装字体

### ISSUE THREAD

**Issue by hanli2016** [wmjordan/PDFPatcher#101]
**请简要描述你遇到的问题**
pdf使用的思源黑体乱码，希望使用字体替换解决，但是替换字体列表里面找不到已安装的思源黑体字体。

word里可以看到思源黑体字体（SourceHanSans）已安装
![word](https://user-images.githubusercontent.com/23231745/166904009-16bb935b-217f-414d-991c-c015a6211f54.png)
替换列表里找不到（SourceHanSans也找不到）
![补丁丁](https://user-images.githubusercontent.com/23231745/166903845-fb378531-6d4b-4f80-a321-36d29ff7626d.png)

**Comment by wmjordan** [comment]
是这样的。由于技术限制，目前 OpenType 字体无法嵌入到 PDF 文档。

**Comment by hanli2016** [comment]
> 是这样的。由于技术限制，目前 OpenType 字体无法嵌入到 PDF 文档。

猜到可能是这个问题，所以也装了ttf版的，也读取不到。
用的这个字体包https://github.com/be5invis/source-han-sans-ttf/releases/tag/v2.002.1

**Comment by wmjordan** [comment]
PDF组件读取不了那字体。真没办法。

**Comment by hanli2016** [comment]
> PDF组件读取不了那字体。真没办法。

好的，只能换其他字体了，感谢。

**Comment by wmjordan** [comment]
是啊，我自己也想替换成思源黑体、思源宋体，但实在没办法 :(
