### ISSUE TITLE
“至少有一个签名需要验证”的问题

### ISSUE THREAD

**Issue by Geo123abc** [wmjordan/PDFPatcher#103]
带签名的PDF文件，“至少有一个签名需要验证” 这个问题怎么解决？

[PDF 文件](https://www.govinfo.gov/content/pkg/GOVPUB-C13-bfd606acc2525ccef2762b19002a6d4f/pdf/GOVPUB-C13-bfd606acc2525ccef2762b19002a6d4f.pdf) 

![存在问题](https://i.bmp.ovh/imgs/2022/05/16/024d748ee7942d38.png)

使用PDF补丁丁处理，无法去除限制，使用的设置不对？还是PDF补丁丁不支持？

**Comment by Geo123abc** [comment]
> 没辙。

啊，这，好吧，我再想想其他方法，谢谢

**Comment by wmjordan** [comment]
昨晚没时间下载你提供的文件。
文档没有用证书加密的话，就可以处理。
PDF 补丁丁本身就能修改这个文档。
如果要让 PDF XChange Editor 编辑该文档，要先清除文档的证书。

目前 PDF 补丁丁没有一键清的工具，但你可以使用文档结构探查器简单地删除掉一些信息来清理掉证书。
先删掉 Trailer 下的 Perms：
<img width="347" alt="image" src="https://user-images.githubusercontent.com/12182730/168711630-089beda5-1c1c-4f0d-984c-5f8c2888d353.png">

再删掉第 1 页的签名批注：
<img width="356" alt="image" src="https://user-images.githubusercontent.com/12182730/168711801-5049fe1b-b293-4716-b22f-f975919a76a1.png">

然后点击工具栏的存盘按钮另存为另一个文件即可。
