### ISSUE TITLE
合并PDF的同时合并PDF里面的大纲（Outline） 

### ISSUE THREAD

**Issue by lelandyang** [wmjordan/PDFPatcher#109]
问题：
---
有时候，网站上的多个PDF其实是由一个PDF拆分得来，里面的大纲项目也被拆分成了从大纲树的一棵子树。在现有情况下，PDFPatcher原封不动的把每一个页面的大纲按原样输出的，并没有合并

其他信息：
---
+ PDFPatcher版本：1.0.0.4033
+ 使用的功能：合并PDF和图片文件
+ 文件样本：[sample.zip](https://github.com/wmjordan/PDFPatcher/files/8831377/sample.zip)

**Comment by wmjordan** [comment]
针对您的应用场合和文档类型，建议您在合并文件后使用 PDF 补丁丁自动生成书签的功能重新生成书签。
