### ISSUE TITLE
持续集成

### ISSUE THREAD

**Issue by calcitem** [wmjordan/PDFPatcher#11]
在进行大变更之前，我先创建一个Issue，然后再做PR，以免工作和其他贡献者的产生重复或冲突。也可大家就此进行讨论，达成共识。

近期计划：

- [ ] 创建yml文件，让Github Action能工作起来。
- [ ] 编译前通过脚本修改签名配置。构建期间进行签名。
- [ ] 调用打包脚本进行打包。
- [ ] 小版本号自动生成。
- [ ] 添加拼写检查Action。
- [ ] 添加代码格式检查Action。
- [ ] 添加Bug报告和新功能请求的Issue模板。

远期计划：

- [ ] 前后端分离，支持命令行调用。
- [ ] 支持通过命令行调用的方式进行集成测试。
- [ ] 持续集成期间进行单元测试和集成测试。

**Comment by wmjordan** [comment]
我觉得编译过程最好能尽量少地依赖生成工具，少装额外的软件。
这个小程序目前编译 Debug 版应该没什么问题了。
参与者要编译个人使用的 Release 版本也不困难，稍微改改也行了。
重要的改进呢，应该着眼于功能上面。

**Comment by calcitem** [comment]
CI编译过程是告诉GitHub需要使用什么容器镜像，不会产生更多的外部依赖。每个sln本身是支持使用命令行编译的。因此不太理解您提到的"依赖生成工具"具体是指？

**Comment by wmjordan** [comment]
是指持续集成工具对本项目的意义似乎不明显

**Comment by calcitem** [comment]
了解了，先close。有需要再reopen。
