### ISSUE TITLE
JBIG2Enc函数参数表类型不一致

### ISSUE THREAD

**Issue by lelandyang** [wmjordan/PDFPatcher#110]
**请简要描述你遇到的问题**
导出函数形参数据类型不一致。

**重现问题的步骤**
步骤如下：
+ 在jbigenc.lossless里，函数原型为：
```c
u8 *
jbig2_encode (int width, int height, int stride, bool zeroIsWhite, uint32_t * const source, int *const length)
```
`source`为uint32_32指针，在函数实现中进行了指针类型转换为uint8_t。
在头文件中，却写成了：
```
uint8_t *
jbig2_encode (int width, int height, int stride, bool zeroIsWhite, uint8_t * const bw, int *const length);
```
`bw`却是`uint8_t`类型。在VS中不会有问题，但是在gcc中却会出现导出函数导出问题。

**预期的结果或行为**
数据类型一致。

**相关截图或文件**
如果有必要，请附上截图或文件（最好能附上程序的界面截图，以便了解你现在使用的版本和操作选项等）

**其它**
与本问题相关的信息

**Comment by wmjordan** [comment]
谢谢告知，已修复。
