### ISSUE TITLE
做个MACOS版的吧

### ISSUE THREAD

**Issue by andylhqiu** [wmjordan/PDFPatcher#112]
**使用场景**
例如：适配MACOS

谢谢

**Comment by wavechao** [comment]
+1

**Comment by lelandyang** [comment]
> **使用场景** 例如：适配MACOS
> 
> 谢谢

嘴一张就要别人做macOS版本，你咋不上天？

**Comment by wmjordan** [comment]
我没有苹果电脑。无法测试。要支持其它操作系统，需要重新编译所有用 C 编写的库，程序本身（界面）也需要做比较多的调整。工作量过于巨大，吃不消。
如果要支持其它操作系统，我也会优先考虑支持国产操作系统。

**Comment by wavechao** [comment]
> 我没有苹果电脑。无法测试。要支持其它操作系统，需要重新编译所有用 C 编写的库，程序本身（界面）也需要做比较多的调整。工作量过于巨大，吃不消。 如果要支持其它操作系统，我也会优先考虑支持国产操作系统。

辛苦了，能支持国产操作系统例如deepin非常棒哈
