### ISSUE TITLE
提取图片未按原PDF文件内顺序命名

### ISSUE THREAD

**Issue by LzNOHentai** [wmjordan/PDFPatcher#114]
版本1.0.0.4064
PDF文件内，第一页是封面，第二页是目录。
提取出来后封面页为0001.jpg，目录页是0001[135].jpg，中间是其他图片。
![image](https://user-images.githubusercontent.com/22359967/177010325-717c39ce-514d-4874-867f-f6a4ad7e851b.png)

**Comment by wmjordan** [comment]
导出文件的命名是按文件在PDF文件内出现的结构顺序（而不是可视顺序）来的，暂时无法支持。

**Comment by LzNOHentai** [comment]
> 导出文件的命名是按文件在PDF文件内出现的结构顺序（而不是可视顺序）来的，暂时无法支持。

这样啊......那有什么其他方法能按可视顺序无损提取原图呢。

**Comment by wmjordan** [comment]
人工调整一下吧。

**Comment by LzNOHentai** [comment]
> 人工调整一下吧。

搜了一下，poppler里的pdfimages命令可以做到按页面显示顺序提取原图，大佬可以参考一下，毕竟这样应该才符合多数人的使用逻辑与需求。
https://github.com/oschwartz10612/poppler-windows

**Comment by wmjordan** [comment]
你发一个不含有少儿不宜的文件给我研究一下吧
