### ISSUE TITLE
自动生成书签之后，西文为全角

### ISSUE THREAD

**Issue by lelandyang** [wmjordan/PDFPatcher#118]
**请简要描述你遇到的问题**
本来应该是怎样的，但实际上却出现了怎样的情形
国内很多出版社采用方正书版排书籍，方正书版的大样文件采用双字节存储文字，所以英文和数字都是用全角保存的。导出的PDF也是如此，所以导致PDFPatcher在生成书签时，英文和数字全都是全角。

**重现问题的步骤**
步骤如下：
1. 使用如下附件 '...' （如有必要，我再附上附件）
2. 打开某功能 '....'
3. 选中哪些选项，点击哪些按钮 '....'
4. 出现的问题

**预期的结果或行为**
在完成上面的操作步骤后，您觉得程序应该是怎样工作的。

**相关截图或文件**
如果有必要，请附上截图或文件（最好能附上程序的界面截图，以便了解你现在使用的版本和操作选项等）

**其它**
与本问题相关的信息

**Comment by wmjordan** [comment]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/12182730/179871698-7c6a6b0d-2892-47dc-8dd5-0d1a478d7052.png">

看附图。
选中所有包含全角字符的书签，改成半角。
