### ISSUE TITLE
提取图片时发生错误

### ISSUE THREAD

**Issue by balthild** [wmjordan/PDFPatcher#119]
**请简要描述你遇到的问题**

**重现问题的步骤**

步骤如下：

1. 下载这个 PDF：https://zh.hk1lib.org/book/3606983/ac7b70 （80.76 MB 的那个版本）
2. 打开上述 PDF，提取图片
3. 在「选项」中，勾选「尝试合并相同页面的图片」
4. 点击「提取图片」按钮，在提取到第 8 页时发生错误。此时输出文件夹里有 0008.png 和 0008[2].png，猜测是因为没有 0008[1].png 导致合并图片出错

**预期的结果或行为**

成功提取图片

**相关截图或文件**

![image](https://user-images.githubusercontent.com/2662758/180222870-473d679b-0bea-4973-bc92-13d3873ceca3.png)

**其它**

无

**Comment by wmjordan** [comment]
请帮忙用“提取页面”功能（见软件首页左侧连接），把第8页提取出来上传到这里吧。

**Comment by balthild** [comment]
[p8.pdf](https://github.com/wmjordan/PDFPatcher/files/9167371/p8.pdf)

**Comment by wmjordan** [comment]
请下载新的测试版

**Comment by balthild** [comment]
确认问题已修复
