### ISSUE TITLE
保存部分pdf时出现错误，提示 堆栈为空 

### ISSUE THREAD

**Issue by JoeScandium** [wmjordan/PDFPatcher#121]
导出阅读器设置。
导出页面连接。
导出命名目标。
完成导出任务。
导入文档属性。
导入文档元数据信息。
修改页面尺寸
PDF 常规处理
在处理文档第 1 页时出错。
堆栈为空。

**Comment by JoeScandium** [comment]
尝试一下午后发现是

**Comment by wmjordan** [comment]
请将导致问题的那个页面提取出来，上传到这里

**Comment by JoeScandium** [comment]
![堆栈为空截图](https://user-images.githubusercontent.com/40695113/182199679-612faa82-2552-47ee-a9b6-11079a27a908.png)
[实例pdf.pdf](https://github.com/wmjordan/PDFPatcher/files/9235691/pdf.pdf)

**Comment by wmjordan** [comment]
这个文档的结构有问题。
`q`和`Q`指令不匹配，后者比前者多了1个。
请下载新的测试版。

**Comment by JoeScandium** [comment]
问题解决了，之前不成功的pdf都正常导出
