### ISSUE TITLE
最新测试版不支持英文字母页码

### ISSUE THREAD

**Issue by MapleCatalpa** [wmjordan/PDFPatcher#122]
RT，加载具有英文字母页码（A, B, C, ...; a, b, c, ...）页面的文档时程序会将这些页面视为没有页码，而虽然在设置页码的窗口中有英文字母页码的选项，但是确定后仍然是没有页码的状态。

**Comment by wmjordan** [comment]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/12182730/182500463-1477ee2a-126f-4217-bc89-4fca4150a763.png">

有页码标签啊

**Comment by wmjordan** [comment]
问题已修复，请下载刚刚发布的测试版。

**Comment by wmjordan** [comment]
<img width="449" alt="image" src="https://user-images.githubusercontent.com/12182730/182989545-c8c3d135-030b-4ab9-af4e-4006a1a81af9.png">

**Comment by wmjordan** [comment]
因无反馈，故关帖，有问题请重开本帖
