### ISSUE TITLE
插入指定大小空白页，同时保持文档原尺寸

### ISSUE THREAD

**Issue by 1-1-2** [wmjordan/PDFPatcher#123]
**使用场景**
场景简述：在合并存在多种尺寸页面的文档的同时，需要插入空白页。
当前问题：当前的功能设计，必须在“功能选项-页面布局”中指定页面尺寸大小，导致了可能的页面缩放。
详述：如需要合并设计图纸，同一本图纸会有A2或者A2加长页。插入空白页目的是在双面打印时起占位符的作用，避免出现封面被打印到双数页（叶背）的情况。

**功能应该怎样实现**

一个想法：为插入空白页添加下拉菜单，放入“插入指定大小空白页”功能。
![设想配图](https://user-images.githubusercontent.com/50569812/186317837-b1bdebba-9ce8-4e43-adf0-3e0ba789d6e2.png)

**类似软件**
Adobe Acrobat DC，其逻辑为默认插入与前一页同尺寸、方向的空白页。
![Acrobat add blank](https://user-images.githubusercontent.com/50569812/186320548-2fdc7eb5-34f9-4b63-b291-5422396fcf98.png)

**Comment by 1-1-2** [comment]
另外还有一个小建议。
在每次添加空白页后，虽然光标高亮在空白页上，但是按键盘下键的时候，会重新从第一个文件开始滚动。
可否修改为在当前高亮的位置上开始滚动？

![现状滚动](https://user-images.githubusercontent.com/50569812/186554161-06b172d6-1c20-4cc1-bbdb-c4a7bddabd76.gif)

**Comment by wmjordan** [comment]
有了一个新版本，暂时未能指定特定页面尺寸，但能使用上一页的尺寸作为后续空白页的尺寸。

**Comment by 1-1-2** [comment]
> 有了一个新版本，暂时未能指定特定页面尺寸，但能使用上一页的尺寸作为后续空白页的尺寸。

也够用了，空白页作为占位符的时候，尺寸问题不大的👍
