### ISSUE TITLE
建议“合并文档”处，有“清除所有文件”按键

### ISSUE THREAD

**Issue by retsyo** [wmjordan/PDFPatcher#127]
**使用场景**
处理多处不同的文件，分别合并到不同pdf

**功能应该怎样实现**
当前只有“删除选中项”按键，如果我处理完了一批文件的合并，想换一批文件合并，那么得先选中当前所有文件，再按“删除选中项”。
所以，建议直接添加一个“清除所有文件”按键，一键完成。

另外，2个问题，还是在“合并文档”tab页面
1）这里有3种风格的按键：1.“文件(J)”，完全使用文字书写；2.“添加文件（T）”、“添加文件夹”、“插入空白页”是文字搭配图标；3.从“删除选中项”到后面，又只有图标。可否统一一下；如果因为空间问题，没法全部做成文字形式，至少我觉得没必要文字搭配图标，部分只用文字，部分只有图标，将2种风格略微在空间上分开一点

2）“文件(J)”、“添加文件（T）”、“添加文件夹”右侧都有一个下拉展开的三角。但是只有只有“文件(J)”的三角是和大众习惯一致的，真的可以点开做选择。“添加文件（T）”、“添加文件夹”右侧的三角不能被点开

**Comment by wmjordan** [comment]
> 当前只有“删除选中项”按键，如果我处理完了一批文件的合并，想换一批文件合并，那么得先选中当前所有文件，再按“删除选中项”。
> 所以，建议直接添加一个“清除所有文件”按键，一键完成。

不要选中文件列表的任何文件，点击工具栏上的删除按钮可以清空列表。
