### ISSUE TITLE
如何在导入文本书签时指定书签缩进标记

### ISSUE THREAD

**Issue by LuckyEvent** [wmjordan/PDFPatcher#129]
有时从网上下载的现成的简易书签文本中，不是按数字模式来区分书签的级别，而是只根据每一行的缩进来区分级别。但是这样的书签文本导入之后，在书签栏里都只显示为同一个级别的书签，并没有把缩进体现成书签的级别。这种书签文本每一行的开头，并没有表示哪章哪节的数字，而只是缩进。如果要体现级别，目前还得按不同的级别在每一行开头手动添加不同级别的数字模式，比较繁琐。

这种只靠缩进，不靠数字模式来体现级别的情况很常见，希望能够在书签功能里加入这个缩进体现级别的功能。

**Comment by wmjordan** [comment]
是不是希望将形如下列级别的书签：
````txt
HHH
    MMMM
    NNNN
III
    JJJJ
    KKKK
````
变成如下形式？
````txt
1. HHH
    1.1 MMMM
    1.2 NNNN
2. III
    2.1 JJJJ
    2.2 KKKK
````

**Comment by LuckyEvent** [comment]
我希望不用添加数字，任何文字的书签，只需要根据它的缩进来判断它的级别。没有缩进的是顶级书签，一个缩进的是子级书签，两个缩进的是3级书签。缩进可以是制表位，也可以是空格，缩进的单位可以定制。比如一个或2个或3个空格为一个缩进，或者1个或2个制表位为一个缩进。

**Comment by LuckyEvent** [comment]
我希望不用添加数字，任何文字的书签，只需要根据它的缩进来判断它的级别。没有缩进的是顶级书签，一个缩进的是子级书签，两个缩进的是孙级书签，3个缩进的是重孙级书签。。。。缩进可以是制表位，也可以是空格，缩进的单位可以定制。比如一个或2个或3个空格为一个缩进，或者1个或2个制表位为一个缩进。
    

    父书签主食 
        子书签米饭
        子书签面食 
            孙书签油条
            孙书签面包
               重孙书签蛋糕
    父书签酒水
        子书签白酒
            孙书签二锅头
        子书签啤酒
            孙书签雪花干啤

上述的文本书签，没有任何文字标识章节级别，但是应该能根据他们不同的缩进自动判断他们的级别。导入PDF文件后，在PDF阅读器中形成能够折叠的分级的书签。

**Comment by LuckyEvent** [comment]
> 我希望不用添加数字，任何文字的书签，只需要根据它的缩进来判断它的级别。没有缩进的是顶级书签，一个缩进的是子级书签，两个缩进的是孙级书签，3个缩进的是重孙级书签。。。。缩进可以是制表位，也可以是空格，缩进的单位可以定制。比如一个或2个或3个空格为一个缩进，或者1个或2个制表位为一个缩进。
> 
> ```
> 父书签主食 
>     子书签米饭
>     子书签面食 
>         孙书签油条
>         孙书签面包
>            重孙书签蛋糕
> 父书签酒水
>     子书签白酒
>         孙书签二锅头
>     子书签啤酒
>         孙书签雪花干啤
> ```
> 
> 上述的文本书签，没有任何文字标识章节级别，但是应该能根据他们不同的缩进自动判断他们的级别。导入PDF文件后，在PDF阅读器中形成能够折叠的分级的书签。

**Comment by wmjordan** [comment]
如果用制表符缩进，你可以点击书签编辑器的粘贴按钮，将用制表符分隔的文本粘贴进去。
在书签文本后，加一个以上的空格或制表符，可指定页码。
如下所示：
````txt
父书签主食 1
	子书签米饭 2
	子书签面食 3
		孙书签油条 4
		孙书签面包 5
			重孙书签蛋糕	6
父书签酒水	7
	子书签白酒	8
		孙书签二锅头	9
	子书签啤酒	111
		孙书签雪花干啤	122
````

**Comment by LuckyEvent** [comment]
您这个是可以的。不过，很多时候，从网上下载的现成的书签文本的“缩进”不是制表符，而是空格，有可能1个空格也可能2个或3个以上空格作为一个缩进。这种情况下，需要把空格先转成制表符，稍嫌麻烦一些了。
能不能“缩进”可以是制表符，也可以是空格，而且几个制表符或几个空格算一级“缩进”，可以设置。

**Comment by wmjordan** [comment]
如果缩进标记不是制表符，而是空格，可以在要缩进的内容前指定缩进标记。
如下所示（“`#缩进标记=`”后面还有两个空格）：

````
#缩进标记=  
父书签主食 1
  子书签米饭 2
  子书签面食 3
    孙书签油条 4
    孙书签面包 5
      重孙书签蛋糕  6
父书签酒水  7
  子书签白酒  8
    孙书签二锅头  9
  子书签啤酒  111
    孙书签雪花干啤  122
````
