### ISSUE TITLE
批量调整PDF功能中的调整页面尺寸功能在新版本中出现问题

### ISSUE THREAD

**Issue by ilcpm** [wmjordan/PDFPatcher#132]
最新的两个版本中（这里截图是次新版的，新版的效果相同），我通过如图所示的方式希望在页PDF的右边增加30%的空白，出现这样的错误
![image](https://user-images.githubusercontent.com/36830343/195041097-fba4e212-25e1-4049-82e7-7f50012389b5.png)

在老版本4091中，同样的参数同样的PDF可以成功执行
![image](https://user-images.githubusercontent.com/36830343/195041729-39839629-540a-47e9-9565-d366e8f48813.png)

这是旧版本实现的效果，右侧增加了30%的空白，可以用来记笔记
![image](https://user-images.githubusercontent.com/36830343/195042087-d10b64b7-a83b-4196-9937-2fb76855c180.png)

**Comment by wmjordan** [comment]
请下载新的测试版

**Comment by ilcpm** [comment]
问题解决，感谢
