### ISSUE TITLE
关于tiff图片的DPI问题

### ISSUE THREAD

**Issue by ilcpm** [wmjordan/PDFPatcher#134]
网上下载的超星的PDF经过图像提取之后，得到的jpg图片的DPI是300，正常

但是我用老马的CEP处理之后的600DPI的tiff纯黑白图片，不管是经过ABBYY识别之后的，还是直接用老马的图片转PDF软件和并之后的PDF，只要是tiff图片，用补丁丁把图片提取出来之后都只有72的DPI了，这个是PDF或者tiff格式本身的问题，还是补丁丁提取出的问题呢？
反过来如果是jpg图片，和并之后再提取，得到的jpg的DPI都是正常的

**Comment by wmjordan** [comment]
发个文件上来看看

**Comment by ilcpm** [comment]
[old.pdf](https://github.com/wmjordan/PDFPatcher/files/9903480/old.pdf)
[new.pdf](https://github.com/wmjordan/PDFPatcher/files/9903481/new.pdf)

如图，两个PDF均为3页，old是超星的原始文件，DPI 300；new是我自己处理之后用ABBYY合成的文件，封面DPI 300 后面两页DPI 600
补丁丁导出的所有的png和tiff图像DPI都只有72，jpg的DPI 300正确，jp2似乎没有DPI参数，但是从尺寸来看DPI仍然只有72
![image](https://user-images.githubusercontent.com/36830343/199071379-b9ea444a-b0b6-4e1e-a822-51fa057c6d66.png)

**Comment by wmjordan** [comment]
文档本身就如此，没法处理。
这是 old.pdf 第二页的结构。
<img width="289" alt="image" src="https://user-images.githubusercontent.com/12182730/199137617-2e474126-c70d-4459-8dfb-6cd83bc3b2c9.png">

从上面可以看到，图像像素是 1904×2656。PDF 文档的媒体框尺寸也是 1904×2656（页面尺寸＝70.0厘米×93.7厘米）。输出图片指令前的矩阵也是 1904×2656。由于该 PDF 文档没有指定页面的每英寸点数，默认的值就是 72。

PDF 内嵌的 JPG 有元数据，所以能读到 300dpi，而其它压缩方式的没有，所以就用默认的 72dpi。

**Comment by ilcpm** [comment]
但是在new里面因为最开始的图片就有DPI，所以合并之后所有的页面尺寸都是正常的

> 而其它压缩方式的没有，所以就用默认的 72dpi

你的意思是，图片在合并PDF的时候因为没有了元数据，所以图片里面没有DPI信息了是吗？而在old里面也没有指定PDF的尺寸？

那new里面是不是同样的，图片里没有DPI信息，但是PDF里加入了尺寸信息？能不能获取PDF的尺寸信息加入到图片里呢

![image](https://user-images.githubusercontent.com/36830343/199174017-c67b3826-8991-4fdf-a48e-f867c41b850d.png)

**Comment by wmjordan** [comment]
> 你的意思是，图片在合并PDF的时候因为没有了元数据，所以图片里面没有DPI信息了是吗？

是的，没有了。

> 而在old里面也没有指定PDF的尺寸？

尺寸就是 MediaBox。默认每 72 个点就是 1 英寸。

> 那new里面是不是同样的，图片里没有DPI信息，但是PDF里加入了尺寸信息？能不能获取PDF的尺寸信息加入到图片里呢

图片的大小是像素。
页面的尺寸是点。
new 文件的结构比较啰嗦，代码量不少。
图片DPI＝实际像素÷页面点数×页面用户单位比例×各种可能的操作符导致图片缩放比例的变化←这个地方最麻烦，代码量很多

**Comment by ilcpm** [comment]
哦哦，原来如此，那就这样吧，谢谢
