### ISSUE TITLE
怎么根据图片base64数值删除pdf中的图片

### ISSUE THREAD

**Issue by nissansz** [wmjordan/PDFPatcher#135]
**使用场景**
例如：在什么场合下会用到这个功能

**功能应该怎样实现**
例如：界面是怎样的，操作方式是怎样的
怎么根据图片base64数值删除pdf中的图片
**类似软件**
是否有类似软件或程序能提供相同的功能

**其它内容**
与本需求相关的其它内容

**Comment by wmjordan** [comment]
这个功能不好开发。即使开发出来了，也非常难使用。

如果是通过点击阅读器界面来指定要删除的图片，可能还好办一些。

**Comment by nissansz** [comment]
可以实现了，但是用处不大，还是通过xml编辑好，再生成pdf好一点
