### ISSUE TITLE
请问能否增加删除页码的功能呢？

### ISSUE THREAD

**Issue by MapleCatalpa** [wmjordan/PDFPatcher#138]
使用Acrobat编辑pdf的时候，可以删除掉一些或者全部页面的页码（编辑后的效果如图）
![image](https://user-images.githubusercontent.com/49485170/201945380-846c90fd-07e9-454d-baa8-11546818021f.png)
![image](https://user-images.githubusercontent.com/49485170/201945572-d9dba975-adc7-4dac-9b1f-40c071d59e03.png)
但是PDFPatcher似乎不支持这项功能，打开同一个文件之后，已删除页码的页面会显示默认的数字页码（从连续的无页码页面的第1页自1编码），如图
![image](https://user-images.githubusercontent.com/49485170/201946132-c1e4bf70-f127-4912-9620-6a3f5ff21782.png)

不知能否适配pdf的这一功能？

**Comment by MapleCatalpa** [comment]
顺便，手动添加书签时能否点击添加书签按钮后自动进入书签名称的编辑模式？当前程序的设计是点击按钮或者按Insert键之后直接在当前层次添加一个名为“书签”的书签，还需要再按F2将其重命名。但是一般情况下很少会仅添加一个“书签”，大部分还是要根据文档内容更名的，因此直接进入重命名模式比较恰当

**Comment by wmjordan** [comment]
> 不知能否适配pdf的这一功能？

请把文件发给我看看。

> 一般情况下很少会仅添加一个“书签”，大部分还是要根据文档内容更名的，因此直接进入重命名模式比较恰当

我回顾了一下代码，发现我之前是写了代码，在手工点击插入书签按钮后，会自动进入编辑书签文本状态的，不记得是出于什么原因，把那行代码给注释了。

**Comment by MapleCatalpa** [comment]
> 请把文件发给我看看。

您好，样例文件较大，请您用下面这个链接下载（24小时仅限1次下载有效）
https://airportal.top/618113/E9O9yebDqB

**Comment by wmjordan** [comment]
请下载新的测试版。

**Comment by wmjordan** [comment]
在编辑器中，用鼠标右键单击页面，在弹出的插入页码标签下拉列表框中选择新增的“无”选项，即可插入不带页码的页码标签。

**Comment by MapleCatalpa** [comment]
> 请下载新的测试版。

感谢您！两个问题现在来看都解决了！
