### ISSUE TITLE
新增加的《删除链接批注的功能》引发崩溃

### ISSUE THREAD

**Issue by kendling** [wmjordan/PDFPatcher#139]
新增加的《删除链接批注的功能》引发崩溃。

**重现问题的步骤**
步骤如下：
1. 打开 PDF
2. 设置修改方式打开“删除链接批注”
3. 保存 PDF 到新的路径
4. 出现的问题“未将对象引用设置到对象的实例。”

**预期的结果或行为**
正常保存 PDF 。

**相关截图或文件**
日志内容：
打开 PDF 文件：D:\!temp\XR819S WLAN AndroidQ Linux-4.9 平台移植指南.pdf。
导入文档属性。
导入文档元数据信息。
删除批注
PDF 常规处理
删除权限控制。
删除文档批注。
在处理文档第 3 页时出错。
未将对象引用设置到对象的实例。
   在 PDFPatcher.Processor.PageProcessorContext.WritePageCommands() 位置 F:\PDF 工具\PDFPatcher\App\Processor\PageProcessorContext.cs:行号 49
   在 PDFPatcher.Processor.PdfProcessingEngine.ProcessDocument(PdfWriter writer, Document document) 位置 F:\PDF 工具\PDFPatcher\App\Processor\PdfProcessingEngine.cs:行号 122
   在 PDFPatcher.Processor.PdfProcessingEngine.ProcessDocument(PdfWriter writer) 位置 F:\PDF 工具\PDFPatcher\App\Processor\PdfProcessingEngine.cs:行号 92
   在 PDFPatcher.Processor.Worker.PatchDocument(Pdf sourceFile, FilePath targetFile, Object infoDoc, ImporterOptions options, PatcherOptions pdfSettings) 位置 F:\PDF 工具\PDFPatcher\App\Processor\Worker.cs:行号 404

**其它**
看了一下代码：
类 RemoveAnnotationProcessor 的 Process 函数设置了 context.IsPageContentModified = true; 。
导致 PdfProcessingEngine 类的 ProcessDocument 函数调用 pc.WritePageCommands(); 函数时，因 _processor 未初始化引起崩溃。
我参考了 ReplaceFontProcessor 类，Process 函数会读取 context.PageCommands 属性，由此初始化 _processor 。

**Comment by wmjordan** [comment]
谢谢告知，请下载新的测试版
