### ISSUE TITLE
请求将 .editorconfig 文件导出并纳入版本控制

### ISSUE THREAD

**Issue by calcitem** [wmjordan/PDFPatcher#14]
目前我本地的 C# 代码格式化配置和此项目的代码不一致，只要一修改和保存，这个文件代码格式就乱了。而我不想调整我本地的配置，一是繁琐，二是有同时维护其他项目的需求。

好在，如果工作区本地有  .editorconfig 文件，那么 Visual Studio 就会优先应用工作区中的格式化配置，覆盖 IDE 自身的配置。

因此特向维护者请求，将您 Visual Studio 的格式化配置导出为 .editorconfig 文件放到本项目的根目录下，提交合并入库。

导出的方法为：进入 `Tools -> Text Editor ->  C# -> Code Style -> General` ， 点击 `Generate .editorconfig file from settings` 按钮，则版本库根目录下就出现了 .editorconfig 文件，请将其提交并推送入库。

非常感谢！

**Comment by wmjordan** [comment]
好的，我有空的话弄一个这个

**Comment by wmjordan** [comment]
看看行不行

**Comment by calcitem** [comment]
非常感谢！可以工作。

**Comment by calcitem** [comment]
我又发现一个问题，看能否帮忙处理一下？
某些文件的实际上未遵循 .editconfig 即您目前 IDE 的配置进行格式化，这样，当我保存的时候，文件还是会格式化引入不少和逻辑无关的差异。
解决方式为，有劳您在 Visual Studio 的 Analyze 中点击 Code Clean up，约几分钟后，所有代码文件就格式化好了，然后再做个提交推送到版本库中。
原来我想自己格式化的，但是发现这样一来我修改的代码量就很大，如推送入库，GitHub将会统计为我贡献了几万行代码，和实际贡献量明显不符，并且 git blame 将会看到很多代码的最后修改者是我。因此还是由您亲自格式化会更好一些。多谢！

**Comment by wmjordan** [comment]
好的，已格式化代码，并将 editconfig 放到了 App 目录
