### ISSUE TITLE
smba网络路径保存位置出错

### ISSUE THREAD

**Issue by FErDaiif** [wmjordan/PDFPatcher#144]
**请简要描述你遇到的问题**
图片批量导出时使用smba网络路径，会出现保存在本地硬盘的情况

**重现问题的步骤**
步骤如下：
1. 提取图片
2. 拖入批量smba协议路径中的PDF
3. 设置输出图片位置为smba协议路径
4. 文件出现在本地硬盘中

**预期的结果或行为**
存放好或者禁止输出到smba协议路径

**相关截图或文件**

[![y80Id.png](https://i.328888.xyz/2022/12/12/y80Id.png)](https://imgloc.com/i/y80Id)

**其它**
应该不是系统问题。。从win10 19xx -win11 22h2 皆有

**Comment by wmjordan** [comment]
请下载新的测试版
