### ISSUE TITLE
在用图片合并为pdf时，是否可以增加调整图片顺序的功能

### ISSUE THREAD

**Issue by timowei** [wmjordan/PDFPatcher#147]
平时要处理不少扫描的图片，把它们整合成一个pdf。

现在用合并文档→添加文件，把图片导入后，图片的名称排列不一定按文件夹里的名称排列来，可能是对首字符的识别和文件夹的有区别，需要手动调整。

但是目前调整图片顺序的功能只能是选中图片，然后上下拖动。在几百页的情况下，在密密麻麻的图片中拖动到合适的位置很麻烦。

是否可以增加把图片拖到指定的某图片的前/后面这个功能呢？至少，给个”移动到最前/最后”的功能。

虽然暂停开发了，但还是希望哪天能重启，谢谢~

**Comment by wmjordan** [comment]
你可以在资源管理器的文件夹里选中要合并的文件，然后一批批地拖放到文件列表栏。

或者点击合并文件功能工具栏上的“文件”按钮，导出文件列表，然后用文本编辑器打开该列表，调整名称为“书签”的项顺序，保存，再用“导入文件列表”功能导入排序后的列表。

**Comment by timowei** [comment]
> 

好的，多谢建议~
