### ISSUE TITLE
替换文字时，不能正确的替换公式中的字母

### ISSUE THREAD

**Issue by tup2339** [wmjordan/PDFPatcher#148]
**请简要描述你遇到的问题**
替换文档的字体，但是在新文档中，所有公式中的字母都消失了。
我注意到输出日志中有一段:
> 加载字体：楷体(替换 AzbukaStd)
> 嵌入字体：KaiTi(1359字)
> 丢失61字：𝐴̇������−��������������l��≪������⋯⁄�µ�����∆���∓≫�⎩⎨⎧⎪������

新文档中丢失的字符远高于61字，我不知道问题是否跟这个有关。
替换的字体支持丢失的字母。

**重现问题的步骤**
步骤如下：
1.打开某个带有公式的文档；
2.在 设置文件修改方式-替换字体 中勾选 嵌入汉字库和允许替换字体；
3.选中文档中的所有字体添加到替换列表，并更换字体；
4.保存文档；
5.新文档中的公式中只剩下数字了。

版本：1.0.0.4134

下图为原文档截图
![20230201141834](https://user-images.githubusercontent.com/39553367/215966982-ea603bb3-dd66-4913-a40e-a0e21044a16d.png)

下图为新文档截图
![20230201142344](https://user-images.githubusercontent.com/39553367/215967382-aee1c5d4-2f56-4bcb-ae97-9e6384f408ff.png)

**Comment by tup2339** [comment]
补充一下，可能跟word公式编辑器有关。把公式中的字母转换成文本就能正确被替换了。
原文档
![20230201144918](https://user-images.githubusercontent.com/39553367/215972678-b77d0e92-9dfb-4663-a9bd-d46616711d92.png)


新文档文档
![20230201145028](https://user-images.githubusercontent.com/39553367/215972711-ea2acdd6-6ab1-4c4c-b96e-0c60297b9ded.png)

**Comment by lelandyang** [comment]
这个和字体相关。MS WORD 公式编辑器使用的字体默认是otf字体，不是ttf

**Comment by tup2339** [comment]
> 这个和字体相关。MS WORD 公式编辑器使用的字体默认是otf字体，不是ttf

不太明白otf与ttf，想请教一下，是不是我安装了otf字体就能正常显示或替换了？我刚刚看了一下，我的字体库确实都是ttf格式的。

**Comment by wmjordan** [comment]
目前只能嵌入TTF字库到PDF文档。OTF格式的处理不了。

**Comment by lelandyang** [comment]
> > 这个和字体相关。MS WORD 公式编辑器使用的字体默认是otf字体，不是ttf
> 
> 不太明白otf与ttf，想请教一下，是不是我安装了otf字体就能正常显示或替换了？我刚刚看了一下，我的字体库确实都是ttf格式的。

一个折中方案是在用word生成PDF之前编辑切换掉默认的CambriaMath。
