### ISSUE TITLE
合并图片为PDF时，dpi不同导致页面有大有小

### ISSUE THREAD

**Issue by cpuopt** [wmjordan/PDFPatcher#150]
**使用场景**
合并图片为PDF时，使分辨率相同但dpi不同的图片呈现在PDF文档中大小一样
![img](https://p.inari.site/usr/369/63ef38ec94720.jpg)
**功能应该怎样实现**
建议在合并文档功能选项中添加复选框，可选忽略图片属性中的dpi，默认按96（像素每英寸）计算大小

**类似软件**
ImageMagick有实现修改图片dpi

**Comment by wmjordan** [comment]
是否可给一些图片来测试一下

**Comment by wmjordan** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/12182730/219613283-0ded57f1-756f-4518-9705-4bc36252baab.png">

试试合并文件时指定页面宽度的选项

**Comment by cpuopt** [comment]
> 

我这合并的图片本身也有大有小的，而且横竖的都有，固定宽度还是不太好。我现在是先用imagemagick设dpi再合并

**Comment by wmjordan** [comment]
请下载新的测试版 #2

**Comment by wmjordan** [comment]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/12182730/219946193-6134a17b-2369-42a5-9494-bfad0aab5737.png">

**Comment by cpuopt** [comment]
感谢，完美解决了
