### ISSUE TITLE
提取图片功能在某些PDF中提取结果为空

### ISSUE THREAD

**Issue by ilcpm** [wmjordan/PDFPatcher#152]
[[近世代数基础][张禾瑞][高等教育出版社][2005.04][13539249][OCR]_1.pdf](https://github.com/wmjordan/PDFPatcher/files/10785026/2005.04.13539249.OCR._1.pdf)

该PDF来自ABBYY的OCR结果，想提取图片对比的时候发现提取不出来，测试了一下发现很多PDF都提取不出来，直接就走完了进度条，测试了最新版和上一个版本都没有用

**Comment by wmjordan** [comment]
收到。问题不难处理。请等待新测试版本。

**Comment by wmjordan** [comment]
请下载新的测试版。

**Comment by ilcpm** [comment]
测试没有问题了，谢谢
