### ISSUE TITLE
不支持高版本的PDF格式

### ISSUE THREAD

**Issue by ilcpm** [wmjordan/PDFPatcher#153]
测试了一下，可以打开PDF 1.7的版本，但是对于 1.7, Adobe Extension Level 8 这类PDF无法打开

[An Experimental Protocol to Support Cognitive Impairment Diagnosis by using_Cilia,Stefano et al_2018 zh.pdf](https://github.com/wmjordan/PDFPatcher/files/10824951/An.Experimental.Protocol.to.Support.Cognitive.Impairment.Diagnosis.by.using_Cilia.Stefano.et.al_2018.zh.pdf)

![image](https://user-images.githubusercontent.com/36830343/221198483-ea0ed6be-7704-4960-9c43-2dae200ea08f.png)
![image](https://user-images.githubusercontent.com/36830343/221198957-b4b1b962-5444-4f1f-9812-8f22ea8d555a.png)

**Comment by wmjordan** [comment]
重复问题，参见 #126
