### ISSUE TITLE
提取页面/拆分文档无法保留原有书签

### ISSUE THREAD

**Issue by MapleCatalpa** [wmjordan/PDFPatcher#156]
**请简要描述你遇到的问题**
RT，无论是否勾选“保留原文档的书签”，导出的文件都没有保留原有标签

**其它**
如果能增加保留原有页码形式的功能就更好了

**Comment by wmjordan** [comment]
原文档的书签要跳转到拆分后的页码，才会保留。
如果书签不是跳转到拆分后的页码，书签就不会出现在拆分后的文档。

**Comment by MapleCatalpa** [comment]
> 原文档的书签要跳转到拆分后的页码，才会保留。 如果书签不是跳转到拆分后的页码，书签就不会出现在拆分后的文档。

不好意思，我没有太明白您的意思，比如说我有一本1-100页的pdf，现在前99页设定了标签而最后一页是个空页，我试图删除，于是在提取页面功能中设定提取范围为“1-99”，但是现在的程序按这样提取出来的新文件是没有任何标签的

**Comment by wmjordan** [comment]
在我这边，拆分后的文档能保留所提取页面的书签，重现不出你提到的问题。
你需要提供更多的信息。例如拆分页码界面的截图。

**Comment by MapleCatalpa** [comment]
您好，我录了一段屏，您可以看一下
https://user-images.githubusercontent.com/49485170/230296914-aef59578-ce8b-4515-b400-01e5b00dba28.mp4

**Comment by wmjordan** [comment]
感谢你的录屏，已经重现出问题。请等待新版本。

**Comment by MapleCatalpa** [comment]
好的，感谢您一如既往地开发这个优秀地工具~

**Comment by wmjordan** [comment]
您好，新的测试版应可修复您提到的问题，无需再取消选中“清理并压缩输出文档”选项了。
