### ISSUE TITLE
某些文档打不开，会闪退(删除AppConfig.json可复现)

### ISSUE THREAD

**Issue by tooyangtoonaive** [wmjordan/PDFPatcher#157]
https://www.bluetooth.com/specifications/specs/core-specification-5-4/

例如这个Core Specification 5.4 的Core_v5.4.pdf(需下载)，通过 文件->打开文件 打开时卡死，过一会闪退

版本1.0.0.4152

**Comment by wmjordan** [comment]
能打开啊。
<img width="449" alt="image" src="https://user-images.githubusercontent.com/12182730/230389497-98196a86-bdb4-418b-a445-4702fbae0772.png">

**Comment by tooyangtoonaive** [comment]
> 能打开啊。 <img alt="image" width="449" src="https://user-images.githubusercontent.com/12182730/230389497-98196a86-bdb4-418b-a445-4702fbae0772.png">

我现在也不能复现了，但在另一台电脑上可以复现，我怀疑和打开次数有关。

其他现象：出现问题时，用任务管理器查看，memory占用瞬间减至几十KB

**Comment by tooyangtoonaive** [comment]
> 能打开啊。 

你把AppConfig.json删除，貌似又可以复现了。

**Comment by wmjordan** [comment]
无法复现。
我测试的时候是用安装包新解压出来的程序，没有AppConfig.json文件。

**Comment by wmjordan** [comment]
你用“事件查看器”看看应用程序错误中是否有和.NET相关的错误记录，里面可能会有堆栈记录。
请把相关记录发上来。

**Comment by tooyangtoonaive** [comment]
> 你用“事件查看器”看看应用程序错误中是否有和.NET相关的错误记录，里面可能会有堆栈记录。 请把相关记录发上来。

[1.txt](https://github.com/wmjordan/PDFPatcher/files/11179309/1.txt)

**Comment by tooyangtoonaive** [comment]
可惜没有调用栈

**Comment by wmjordan** [comment]
是不是你硬盘有坏道了？

**Comment by tooyangtoonaive** [comment]
> 是不是你硬盘有坏道了？

没道理两台都有问题啊

**Comment by tooyangtoonaive** [comment]
> 是不是你硬盘有坏道了？

https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4659.pdf
你看看这个能不能复现。

**Comment by wmjordan** [comment]
还是复现不了。

<img width="446" alt="image" src="https://user-images.githubusercontent.com/12182730/232690234-6711d0f8-d6c7-417e-805b-a3529eb92753.png">

**Comment by wmjordan** [comment]
请试试下载最新的测试版看看

**Comment by wmjordan** [comment]
无法重现故障
