### ISSUE TITLE
程序不支持书签内换行

### ISSUE THREAD

**Issue by MapleCatalpa** [wmjordan/PDFPatcher#158]
**请简要描述你遇到的问题**
通过Acrobat添加的书签可以在内部换行（如图所示）
![image](https://user-images.githubusercontent.com/49485170/230707234-e6cea318-4868-4028-9988-4a68f7cf6a5c.png)

但是本软件并不支持这一功能
![image](https://user-images.githubusercontent.com/49485170/230707253-c05399a1-3edb-4024-a6a1-dcd9e15687a2.png)
在书签重命名时能发现换行位置有一个肉眼不可见的字符，用shift+左右箭头选中后复制，在另一标签中也粘贴不上这一换行符

**Comment by MapleCatalpa** [comment]
附书签带换行的样例文件一个（仅抽取了该书签所在页面）
[example.pdf](https://github.com/wmjordan/PDFPatcher/files/11182691/example.pdf)

**Comment by wmjordan** [comment]
这个得重写一个支持换行的树型表格控件才行。
工作量不小呢。
谁知道有现成的、好使的控件吗？

**Comment by MapleCatalpa** [comment]
> 这个得重写一个支持换行的树型表格控件才行。 工作量不小呢。 谁知道有现成的、好使的控件吗？

我觉得也不一定现在就完美支持，但是可以先用\n这样的转义字符表示换行符，这样在别的软件上还可以看

**Comment by lelandyang** [comment]
> 这个得重写一个支持换行的树型表格控件才行。 工作量不小呢。 谁知道有现成的、好使的控件吗？

能否继承之后overwrite呢？

**Comment by wmjordan** [comment]
> 可以先用\n这样的转义字符表示换行符

这倒是可行的。


> > 这个得重写一个支持换行的树型表格控件才行。 工作量不小呢。 谁知道有现成的、好使的控件吗？
> 
> 能否继承之后overwrite呢？

那个表格控件是 ListView，Win32 的列表控件怎样搞都不支持多行。

**Comment by wmjordan** [comment]
> 可以先用\n这样的转义字符表示换行符

这倒是可行的。


> > 这个得重写一个支持换行的树型表格控件才行。 工作量不小呢。 谁知道有现成的、好使的控件吗？
> 
> 能否继承之后overwrite呢？

那个表格控件是 ListView，Win32 的列表控件怎样搞都不支持多行。

**Comment by wmjordan** [comment]
> > 这个得重写一个支持换行的树型表格控件才行。 工作量不小呢。 谁知道有现成的、好使的控件吗？
> 
> 我觉得也不一定现在就完美支持，但是可以先用\n这样的转义字符表示换行符，这样在别的软件上还可以看

虽然现在的控件无法支持显示多行书签，但是要为具有多行文本的书签加个标识，支持编辑多行书签，倒是可以做到的。
目前正在内部测试之中，请等新版本发布。
<img width="449" alt="image" src="https://user-images.githubusercontent.com/12182730/230776854-60fe84e7-167e-4d01-89f8-27c9492efe2c.png">
<img width="423" alt="image" src="https://user-images.githubusercontent.com/12182730/230776831-a9704dc1-dbb7-420f-86a4-bb3b20698c38.png">

**Comment by wmjordan** [comment]
请下载新的测试版。

如果要在编辑书签的过程中插入换行，按Shift＋Enter键或Ctrl＋Enter键。
编辑过程中插入了第一个换行后，后面按Enter键即可插入换行。
编辑原有换行的书签可直接按下Enter键换行。
编辑没有换行的书签文本时，按下Enter键将确认编辑，不插入换行。
