### ISSUE TITLE
最新版的补丁丁导出的图片与XPDF工具和Spire.Doc导出的数量不一样

### ISSUE THREAD

**Issue by Charltsing** [wmjordan/PDFPatcher#160]
哦，我知道了，需要勾选导出图像掩模。

Spire.PDF 比较好，它把图片和掩模合到一起，搞成了透明图，输出png，也许补丁丁可以参考一下这个做法。

**Comment by Charltsing** [comment]
哦，我知道了，需要勾选导出图像掩模。

**Comment by wmjordan** [comment]
要是合成到一起，就有损了。

不过，从使用者的便利度来看，倒是可以考虑的。

**Comment by Charltsing** [comment]
> 要是合成到一起，就有损了。
> 
> 不过，从使用者的便利度来看，倒是可以考虑的。

按道理来说，png是无损的，把img和mask叠加到一起，根据mask做成透明图，我觉得也不算有损。
导出个黑色的mask也没什么用处。

**Comment by lelandyang** [comment]
> > 要是合成到一起，就有损了。
> > 不过，从使用者的便利度来看，倒是可以考虑的。
> 
> 按道理来说，png是无损的，把img和mask叠加到一起，根据mask做成透明图，我觉得也不算有损。 导出个黑色的mask也没什么用处。

这就看你如何定义无损了。显然，作者所说的无损指的是raw，即从PDF直接导出的、没有修改的内容。

**Comment by wmjordan** [comment]
今晚做了一个测试版。
在提取图片时先选中“导出图像掩膜”，再导出图片。程序会尝试将导出的图像和掩膜合成一个带有“merged”的图片文件。
请测试一下看看是否能正常合成导出图片文件为透明文件。

**Comment by Charltsing** [comment]
[艺术哲学.zip](https://github.com/wmjordan/PDFPatcher/files/11925033/default.zip)
勾选掩膜之后，导出是黑色的背景

**Comment by wmjordan** [comment]
新的测试版修复了一个导致导出黑白图片反相的错误。请测试一下看看。
上面的样本文档太大了，家里宽带很慢。请用提取页面功能，提取有问题的页面，发上来即可。

**Comment by Charltsing** [comment]
好像没什么问题了。
