### ISSUE TITLE
提取圖片會順序錯亂

### ISSUE THREAD

**Issue by a73420521** [wmjordan/PDFPatcher#167]
我於DLsite上購買成人漫畫，提取圖片時若不勾選「避免導出相同圖片」的話，會無限的輸出以及順序錯亂，若有勾選的話則是只有圖片順序錯亂，請問要怎麼設定才不會讓圖片的順序跑掉?

![1](https://github.com/wmjordan/PDFPatcher/assets/87113124/e494c04a-8989-486b-b031-135acbeb40e9)
![2](https://github.com/wmjordan/PDFPatcher/assets/87113124/df11e9da-aae6-4f10-91eb-4a08b47b9dd4)
![3](https://github.com/wmjordan/PDFPatcher/assets/87113124/bb0b61e0-0b80-4493-a1a8-1ddc1c932419)

**Comment by MY1L** [comment]
路过。以前用DLsite提供的免费体验版pdf测试过，导出图片都很正常。
你的这个情况，是每个DLsite的pdf都是这样，还是个别pdf如此？（如果是个别pdf，需要提供相应的pdf例子）

**Comment by a73420521** [comment]
> 路过。以前用DLsite提供的免费体验版pdf测试过，导出图片都很正常。 你的这个情况，是每个DLsite的pdf都是这样，还是个别pdf如此？（如果是个别pdf，需要提供相应的pdf例子）

我買了幾本試了一下，很像2021年後出的都有這個問題

**Comment by MY1L** [comment]
主要我用DL上免费试阅版测试的，不好提供准确意见。感觉wmjordan没回复也许是不了解DL这个网站，你可能得给他提供此类样本方便检查……🤔

**Comment by wmjordan** [comment]
貌似和 #181 类似。未来发行的新版本里，有一个“只导出可见图片”的选项，应该可以解决这个问题。
