### ISSUE TITLE
【提取图片】软件是否强行输出JPG格式的？勾选了两个PNG相关的选项输出依然是JPG

### ISSUE THREAD

**Issue by gsxgmpkt9020** [wmjordan/PDFPatcher#171]
<img width="581" alt="Snipaste_2023-06-23_08-32-11" src="https://github.com/wmjordan/PDFPatcher/assets/2074641/0e949a4a-7d71-4169-9569-09619e153ac7">

- 确定PDF大部分图片是黑白的，少部分是彩色的。但输出后都是JPG
- 勾选了两个PNG相关的选项输出依然是JPG
- 为什么【提取图片】会出现“合并”相关的选项？让人摸不着头脑。难道是合并成单文件多页的图像格式？（但是没有可选项）强烈建议完善下文档

**Comment by wmjordan** [comment]
如果文档里面的图片是JPEG压缩的，输出的图片就会自动采用JPEG压缩。
选项中间的“黑白图片”是指只有黑色和白色两种颜色的图片。你的文档的“黑白图片”可能是带有灰色的灰度图片。这种灰度图片使用JPEG压缩也可能取得比较高的压缩率。
合并选项是针对一些古老的PDF文档设计的，那个时代的PDF制作工具会把一幅图片切成一条条再写入PDF文档，渲染的时候由于一条条图片是紧挨在一起的，所以看起来是一张图片。“合并”功能是把这种紧挨在一起的一条条的图片合并成一张图片。

**Comment by wmjordan** [comment]
PDF里的图片都是不透明的。
如果图片是使用Deflate、LZW等算法压缩的，一般会被导出成PNG格式。

所谓的“透明”图片是通过图像掩膜来实现的。例如下面附件文档中的“ABC”，实际是一幅图片加一个带灰度的掩膜，掩膜的灰度会被视为透明度。

[文字文稿1.pdf](https://github.com/wmjordan/PDFPatcher/files/11844512/1.pdf)


在渲染文档的时候，将图片和掩膜通过图层混合来呈现出“透明”的效果。

<img width="437" alt="image" src="https://github.com/wmjordan/PDFPatcher/assets/12182730/f3d535e3-a0d7-4d0a-acdf-1dbd4de15cdf">

目前还没有自动合成图片＋掩膜→透明图片的功能。原理很简单，不难实现，不过要花点时间才行。

**Comment by wmjordan** [comment]
今晚刚做了一个可以合并图片＋掩膜成为透明图片的功能。如果你的PDF有透明图，可下载新的测试版测试一下（提取图片前选中“导出图像掩膜”）。
