### ISSUE TITLE
合并文档不支持doc/docx?

### ISSUE THREAD

**Issue by shuai-zhou** [wmjordan/PDFPatcher#175]
**使用场景**
例如：有多分doc/docx需要合并成一个pdf文件，但是合并文件的时候支持的文件并不包含doc/docx

**功能应该怎样实现**
例如：如果有多个doc/docx需要合并成一个pdf文件，先将doc/docx转换成pdf，然后合并

**类似软件**
Adobe Acrobat

**Comment by wmjordan** [comment]
解析Doc和Docx可不是简单的事情。没个几十万的投入，做不了这个功能。
目前Microsoft Word 和 Windows 系统自带的 Print to PDF 都可以将Docx转换成PDF，转换后再合并吧。

**Comment by lelandyang** [comment]
NPOI似乎可以实现WORD转PDF.
