### ISSUE TITLE
希望能优化一下添加书签(目录)功能

### ISSUE THREAD

**Issue by li54426** [wmjordan/PDFPatcher#176]
**使用场景**
阅读pdf, 但是 pdf没有目录, 已经有别人做好的目录列表

**功能应该怎样实现**
[希望添加的逻辑能像这个一样](https://github.com/ifnoelse/pdf-bookmark)

**类似软件**
https://github.com/ifnoelse/pdf-bookmark

**其它内容**
无

**Comment by wmjordan** [comment]
有目录列表的话，复制粘贴到书签栏，保存文档就行啦。
<img width="451" alt="image" src="https://github.com/wmjordan/PDFPatcher/assets/12182730/0594e514-cba4-4179-a5ca-e3908874f1ca">
