### ISSUE TITLE
在合并文件的文件列表下列出文件数量和页数总数

### ISSUE THREAD

**Issue by sicifus** [wmjordan/PDFPatcher#18]
首先感谢大大开源~

以下问题前期和大大反馈过，不知是否能加入近期的ToDo-List？谢谢！
“在【合并文件】模块，列表能否体现一下待合并PDF的文件合计数、页数合计数？”

**Comment by wmjordan** [comment]
我忘记了为什么要加这个文件计数和页数统计了。

**Comment by calcitem** [comment]
建议可以考虑定一个功能需求的模板，更有助于描述清晰完整，减少来回沟通。

**您的功能请求是否与问题有关？ 请描述。**
 对问题所在的清晰简洁的描述。 前任。 当 [...] 时，我总是感到不方便。

 **描述您想要的解决方案**
 对您想要发生的事情的清晰简洁的描述。

 **描述您考虑过的替代方案**
 对您考虑过的任何替代解决方案或功能的清晰简明描述。

 **附加上下文**
 在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by sicifus** [comment]
> 我忘记了为什么要加这个文件计数和页数统计了。

方便的话您可以查一下20210731~0801的邮件，发件人是kuangft2000#163.com。

**Comment by calcitem** [comment]
建议开源后，后续社区成员尽量在论坛交流细节，广泛分享。

**Comment by wmjordan** [comment]
这个功能并不难实现，但是要改动的地方还是蛮多的，估计要耗费我一个多小时来编码和测试。
我翻查了邮件记录，您只提到了有这么个统计，但没说明为什么要加上它。
是否可以说明一下这个功能的应用场景？

**Comment by sicifus** [comment]
> 这个功能并不难实现，但是要改动的地方还是蛮多的，估计要耗费我一个多小时来编码和测试。 我翻查了邮件记录，您只提到了有这么个统计，但没说明为什么要加上它。 是否可以说明一下这个功能的应用场景？

大大你好，我们经常碰到的场景是：1）第一步将CAD或VISIO文件批量转换为PDF文件（每个CAD/VISIO文件内有多张图，分别保存为独立的单个PDF文件）；2）第二步将众多（数百张~数千张）的单个PDF合并为1个大的文件；3）通过工具将这些CAD/DWG文件的图名+图号自动导出生成为图纸目录。

由于软件转换和手动操作的稳定性不太可靠，在第一步时经常会发生丢图或转图失败（无提示）的问题，在第二步时会出现漏并某些文件的问题。

如果在补丁丁里合并PDF时能显示文件合计数、页数合计数，那么我们将大幅减少核查、校验的工作量，只需与第三步生成的目录相比对就行了。
谢谢您。

**Comment by wmjordan** [comment]
> 第一步时经常会发生丢图或转图失败（无提示）的问题

不是应该把这个源头问题给解决掉吗？

**Comment by TroyDanielFZ** [comment]
我明白他的意思，我举个例子吧。
我使用命令行把其它格式的文件转换成PDF，但是由于程序/脚本不稳定，或者错误处理不好做，所以希望在合并的时候，核一下总数。就不用一个一个PDF去看了。@wmjordan

也提供另外一个解决方案，使用Total commander，自定义列，可以查看PDF的页数，得到期望的效果。@sicifus

**Comment by sicifus** [comment]
我们是传统行业里的一个小公司里的一个小团队，第一步源头的那个工具没有修复能力了。@wmjordan 
同时感谢@TroyDanielFZ 提供的一个思路。

但不管第一步怎么控制质量，第二步仍然存在人为并图遗漏的可能，所以希望能通过合并结果时的数据来辅助校验。
谢谢两位集思广益。

**Comment by wmjordan** [comment]
> 通过合并结果时的数据来辅助校验

如果在合并完成后，输出：
````
 已合并 ×× 个文件共 × 页到 ×××.pdf。
````

是否会方便你们校验？

**Comment by sicifus** [comment]
> > 通过合并结果时的数据来辅助校验 
> 如果在合并完成后，输出： 
> ```
>  已合并 ×× 个文件共 × 页到 ×××.pdf。
> ``` 
> 是否会方便你们校验？

方便的，谢谢您！

**Comment by wmjordan** [comment]
好的，这样我就不用花个吧小时来搞原先的需求了

**Comment by wmjordan** [comment]
请下载新的测试版。
