### ISSUE TITLE
提取PDF图片报错 Unable to load DLL 'jbig2.dll'

### ISSUE THREAD

**Issue by ijvim** [wmjordan/PDFPatcher#185]
**请简要描述你遇到的问题**
使用 FreePic2Pdf 中的  JBig2无损 压缩合成的 pdf,  PDFPather 执行提取图片操作时提示错误 

```
Unable to load DLL 'jbig2.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

在 exe 文件目录以及windows 系统目录下都放置了 jbig2.dll 文件

<img width="781" alt="image" src="https://github.com/wmjordan/PDFPatcher/assets/100009823/2df1df0d-99ca-4bdf-8040-c5f27d89b66b">

<img width="1058" alt="image" src="https://github.com/wmjordan/PDFPatcher/assets/100009823/c8327a9f-edc1-45fc-a743-3842d79125a7">

<img width="927" alt="image" src="https://github.com/wmjordan/PDFPatcher/assets/100009823/6060bc0a-e924-4cf0-bdcb-77dab264357b">

图片提取测试文件:

[CCITTG4图片压缩.pdf](https://github.com/wmjordan/PDFPatcher/files/13055227/CCITTG4.pdf)

[JBig2无损图片压缩.pdf](https://github.com/wmjordan/PDFPatcher/files/13055228/JBig2.pdf)

**Comment by wmjordan** [comment]
不需要将 jbig2.dll 放到 Windows 目录下。

在我的机器上可以导出这批图片。
配置界面如下。
<img width="447" alt="image" src="https://github.com/wmjordan/PDFPatcher/assets/12182730/d0e48991-4fe7-43c4-8c56-40067842695a">

**Comment by ijvim** [comment]
在我的机器上面还是报错. 

> 会不会是与我使用虚拟机有关? (Mac上面使用 Windows 11 虚拟机运行 ).
> 会不会是我的 `jbig2.dll` 文件有问题呢? 这个 `jbig2.dll` 文件我是从网上随便下载的.
> CCITTG4 的 pdf 中图片可以正常导出/提取出为 tif.

<img width="923" alt="image" src="https://github.com/wmjordan/PDFPatcher/assets/100009823/b15b9f7c-e122-4dd5-b4ed-db061c133a05">

<img width="926" alt="image" src="https://github.com/wmjordan/PDFPatcher/assets/100009823/12628ff1-1a7e-40f9-b626-e1bba7f2f31d">

**Comment by wmjordan** [comment]
不能随便找jbig2.dll。
PDF补丁丁发布的程序包中有这个文件。请使用发布包里的jbig2.dll。

**Comment by ijvim** [comment]
重新下载最新版本 https://www.cnblogs.com/pdfpatcher/

在我的机器上面依然报错 

<img width="904" alt="image" src="https://github.com/wmjordan/PDFPatcher/assets/100009823/ff6e0f67-e1b1-47c5-bfdf-b673f57faa48">

<img width="600" alt="image" src="https://github.com/wmjordan/PDFPatcher/assets/100009823/168fbba2-5b93-443c-a020-fe53c725986c">

可能是我用虚拟机的问题 , 导出我用其他 Windows 电脑导出算了
