### ISSUE TITLE
Win10图片 旋转的 jpg 无法正常获取

### ISSUE THREAD

**Issue by hakutyou** [wmjordan/PDFPatcher#188]
**请简要描述你遇到的问题**
合并文件功能， 使用 Win10图片 旋转的 jpg 无法正常获取

**相关截图或文件**
![image](https://github.com/wmjordan/PDFPatcher/assets/5998509/d8e1bcf0-fecb-4659-91cb-16ccc15cecb3)
![image](https://github.com/wmjordan/PDFPatcher/assets/5998509/89a0860f-bd20-47eb-9902-db07fc14494e)

**Comment by hakutyou** [comment]
重写了一个 TryGetExifOrientation
```csharp
		// App/Processor/Imaging/JpgHelper.cs
		internal static bool TryGetExifOrientation(string fileName, out ushort b) {
			b = 0;
			try {
				var image = Bitmap.FromFile(fileName);
				var exif = image.PropertyItems;
				var item = exif.Where(m => m.Id == 0x112).ToArray();
				if (item.Length > 0) {
					b = item[0].Value[0];
				}
				return true;
			}
			catch (Exception) {
				b = 0;
				return false;
			}
		}

		// 原来的
		internal static bool _TryGetExifOrientation(string fileName, out ushort b) {
			try {
				using (var r = new ExifReader(fileName)) {
					return r.GetTagValue(ExifTags.Orientation, out b);
				}
			}
			catch (Exception) {
				b = 0;
				return false;
			}
		}
```

**Comment by lelandyang** [comment]
> 重写了一个 TryGetExifOrientation
> 
> ```cs
> 		// App/Processor/Imaging/JpgHelper.cs
> 		internal static bool TryGetExifOrientation(string fileName, out ushort b) {
> 			b = 0;
> 			try {
> 				var image = Bitmap.FromFile(fileName);
> 				var exif = image.PropertyItems;
> 				var item = exif.Where(m => m.Id == 0x112).ToArray();
> 				if (item.Length > 0) {
> 					b = item[0].Value[0];
> 				}
> 				image.Dispose();
> 				return true;
> 			}
> 			catch (Exception) {
> 				return false;
> 			}
> 		}
> 
> 		// 原来的
> 		internal static bool _TryGetExifOrientation(string fileName, out ushort b) {
> 			try {
> 				using (var r = new ExifReader(fileName)) {
> 					return r.GetTagValue(ExifTags.Orientation, out b);
> 				}
> 			}
> 			catch (Exception) {
> 				b = 0;
> 				return false;
> 			}
> 		}
> ```

如果exif信息不存在似乎这段代码就不行了。

**Comment by wmjordan** [comment]
收到，等我有时间看看是什么回事

**Comment by wmjordan** [comment]
请把测试用的文件上传到这里吧

**Comment by hakutyou** [comment]
[测试.zip](https://github.com/wmjordan/PDFPatcher/files/13291949/default.zip)

**Comment by hakutyou** [comment]
> 请把测试用的文件上传到这里吧

[测试.zip](https://github.com/wmjordan/PDFPatcher/files/13291951/default.zip)

**Comment by hakutyou** [comment]
> 请把测试用的文件上传到这里吧

[测试.zip](https://github.com/wmjordan/PDFPatcher/files/13291959/default.zip)

**Comment by wmjordan** [comment]
用 Bitmap 加载图片来读取 EXIF 属性会产生比较大的开销，问题出在 ExitReader 里，调整一下就行了。
感谢提供测试样本文件。已修复该问题，请等下一版发布。
