### ISSUE TITLE
命名连接有误导致文档无法打开

### ISSUE THREAD

**Issue by zwo1a** [wmjordan/PDFPatcher#192]
**请简要描述你遇到的问题**
无法打开此文档
https://wjw.fujian.gov.cn/xxgk/zfxxgkzl/zfxxgkml/wszh/yzgl/202301/P020230117416874794347.pdf

**重现问题的步骤**
步骤如下：
1. 使用如下附件：https://wjw.fujian.gov.cn/xxgk/zfxxgkzl/zfxxgkml/wszh/yzgl/202301/P020230117416874794347.pdf
2. 用 PDFPatcher 打开此文档
3. 弹出错误提示如下，文档无法打开：
在打开 PDF 文件时遇到错误：
无法将类型为“iTextSharp.text.pdf.PdfName”的对象强制转换为类型“iTextSharp.text.pdf.PdfString”。

**预期的结果或行为**
文档正常打开并显示

**相关截图或文件**
![图片](https://github.com/wmjordan/PDFPatcher/assets/154390381/9739948d-81ee-4655-a089-7425f8c1f55d)

**其它**
Wndows 10 21H2 x64
PDFPatcher 1.0.0.4200

**Comment by newyb** [comment]
该PDF用EDGE 112.0.1722.39 (正式版本) (64 位)
WPS 2023冬季更新（15990）均可正常打开

**Comment by wmjordan** [comment]
源文件有一些轻微的问题，导致打开时出错。
请访问程序主页下载新发布的版本。该版本暂时绕过这个问题。

**Comment by wmjordan** [comment]
我刚刚上传了一个新的版本解决了这个问题。
