### ISSUE TITLE
打开特定PDF进行编辑时，pdfpatcher崩溃退出

### ISSUE THREAD

**Issue by sulisu** [wmjordan/PDFPatcher#196]
**请简要描述你遇到的问题**
使用最新的PDFPatcher.1.0.1.4220.7z。打开文档编辑器，打开“数据安全治理白皮书5.0——行业数据安全治理实践集.pdf”，打开过程中，程序崩溃，自动退出。

**重现问题的步骤**
步骤如下：
1. 使用如下附件：从这里<https://www.digitalelite.cn/h-nd-6564.html>下载“数据安全治理白皮书5.0——行业数据安全治理实践集.pdf”，直接下载无需注册
2. 打开某功能 '....'：文档编辑器
3. 选中哪些选项，点击哪些按钮 '....'：点击“打开需要编辑的PDF文件”按钮，选择上述pdf文件，打开。
4. 出现的问题：程序开始打开该文件，界面有变化，但是最终直接退出，尝试多次均如此。未测试其他电脑上的环境，但软件其他功能正常，可以正常编辑其他pdf文件。使用文档结构探查器打开该文件正常。

**预期的结果或行为**
在完成上面的操作步骤后，您觉得程序应该是怎样工作的。
正常打开该pdf文件。

**相关截图或文件**
如果有必要，请附上截图或文件（最好能附上程序的界面截图，以便了解你现在使用的版本和操作选项等）
PDFPatcher.1.0.1.4220.7z
windows 10 专业版，22H2

**其它**
与本问题相关的信息
无

**Comment by wmjordan** [comment]
我这边无法重现故障

<img width="454" alt="image" src="https://github.com/wmjordan/PDFPatcher/assets/12182730/5a2df5d5-cc60-4ad3-ab4a-1f0b578592fb">

**Comment by sulisu** [comment]
确实，我找到另一台电脑，在上面就能正常打开了。麻烦您啦，祝您新年快乐。

这是有问题电脑上的应用崩溃报告wer文件。

[Report.zip](https://github.com/wmjordan/PDFPatcher/files/14310106/Report.zip)

**Comment by wmjordan** [comment]
从 Report.zip 文件看不出是什么原因导致崩溃。请看看系统的事件查看器是否有和“.NET Runtime”相关的错误记录。

**Comment by sulisu** [comment]
> 从 Report.zip 文件看不出是什么原因导致崩溃。请看看系统的事件查看器是否有和“.NET Runtime”相关的错误记录。

在事件查看器里加了.NET Runtime来源的日志，但程序崩溃时没有新日志出现。可能是和这个电脑的特有配置有关系，不是普遍性问题。
