### ISSUE TITLE
嵌入字体遇到报错

### ISSUE THREAD

**Issue by luojineng** [wmjordan/PDFPatcher#197]
嵌入汉字库
PDF 常规处理
加载字体：宋体(替换 STSong-Light-GBK-EUC-H)
在处理文档第 169 页时出错。
无法将类型为“iTextSharp.text.pdf.PdfNumber”的对象强制转换为类型“iTextSharp.text.pdf.PdfString”。

**Comment by wmjordan** [comment]
请用“提取页面”功能把该文档第169页提取出来发到这里

**Comment by luojineng** [comment]
查看发现是那页内容损坏导致。抱歉。
