### ISSUE TITLE
文件夹内奇数页的pdf自动插入空白页

### ISSUE THREAD

**Issue by hou6807628** [wmjordan/PDFPatcher#198]
我有许多pdf文件，我需要双面打印。我希望可以自动将文件夹内的奇数页pdf文件在最后插入一张空白页，然后合并起来。
这样可以实现吗？谢谢

**Comment by wmjordan** [comment]
已实现该功能，请到程序的下载空间下载新的4239测试版

**Comment by wmjordan** [comment]
已实现该功能，请到程序的下载空间下载新的4239测试版

**Comment by hou6807628** [comment]
已下载测试文件，300多个文件，目前运行正常，感谢！
