### ISSUE TITLE
PDF 补丁丁1.0 测试版下载

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/PDFPatcher#2]
## 说明
感谢您关注 PDF 补丁丁，请在使用软件或源代码前阅读说明和授权协议。本软件及源代码采用“良心授权”协议——**用户每次使用本软件后如有所获益，应行一善事；如使用源代码开发了新的软件并获得收益，应将收益中不低于千分之一的金额捐赠给社会的弱势群体**。

## 下载
[PDFPatcher.1.0.0.4187.7z.zip](https://github.com/wmjordan/PDFPatcher/files/11868350/PDFPatcher.1.0.0.4187.7z.zip)

[PDFPatcher.1.0.0.4185.7z.zip](https://github.com/wmjordan/PDFPatcher/files/11856945/PDFPatcher.1.0.0.4185.7z.zip)
[PDFPatcher.1.0.0.4182.7z.zip](https://github.com/wmjordan/PDFPatcher/files/11587184/PDFPatcher.1.0.0.4182.7z.zip)
[PDFPatcher.1.0.0.4172.7z.zip](https://github.com/wmjordan/PDFPatcher/files/11258550/PDFPatcher.1.0.0.4172.7z.zip)
[PDFPatcher.1.0.0.4153.7z.zip](https://github.com/wmjordan/PDFPatcher/files/11182253/PDFPatcher.1.0.0.4153.7z.zip)
[PDFPatcher.1.0.0.4142.7z.zip](https://github.com/wmjordan/PDFPatcher/files/10789346/PDFPatcher.1.0.0.4142.7z.zip)
[PDFPatcher.1.0.0.4140.7z.zip](https://github.com/wmjordan/PDFPatcher/files/10778541/PDFPatcher.1.0.0.4140.7z.zip)
[PDFPatcher.1.0.0.4137.7z.zip](https://github.com/wmjordan/PDFPatcher/files/10776766/PDFPatcher.1.0.0.4137.7z.zip)

## 更新内容

- 合并图片功能使用JPEG图片EXIF旋转角度（3727）
- 增加合并文档过程是否尝试清除冗余数据的选项（3789）
- 增加在使用过程中不再提示打开文档权限的操作办法（3828，#81 ）
- 合并文件功能的“文件”菜单增加排序文件功能（3843, #86）
- 自动生成书签功能增加标题跳转到页首的选项（3851, #87）
- 合并文件功能在日志窗口输出目标文件由多少个文件共多少页合并而成（3860, #18 ）
- 编辑器允许保存和读取“自动生成书签”功能中的筛选条件（3860，3864，#32）
- 编辑器“自动生成书签”功能增加书签文本筛选条件（4026，#16 ）
- 优化高分辨率显示器上的表格列宽（4033，#77 ）
- 记住窗口的大小和位置（4064，#108）
- 调整识别文本功能默认的识别结果格式，在识别结果文件不是 XML 时给出提示
- 提高文档结构探查器和文档处理器的容错能力（4087，#121）
- 合并文档使用上一页的尺寸作为空白页尺寸（4105）
- 合并文档对话框在添加项后将焦点移动到文本列表框（4105）
- 增加合并图片时覆盖原图片分辨率的选项（#150）
- 将编辑器的修改文档选项菜单项移到阅读器工具栏（#149）
- 优化书签编辑器编辑多行书签（#158）
- 导出二进制流到文件（4182，#161）
- 提取图片功能可使用掩膜合成透明图片（#160）
## 修复问题
- 书签编辑器页码编辑框太窄（3730, 3755）
- 合并文件功能在添加的目录存在无访问权限文件或子目录时导致程序崩溃（3755）
- 合并文件在某些场合下会丢失数据（3788）
- 导出信息文件功能的输出文件名不正确（3794）
- 导入多页TIF图片时所有页面全为第一页（3799）
- 合并文件功能没有正常处理带调色板的图片（3800, 3802，3815）
- 打开破损PDF文档时会崩溃（3823）
- 无法导入带有控制字符的书签文件（3829, #82 ）
- 无法识别或提取某些 PDF 文档文本（3831, #83）
- 无法导出某些图片（3846）
- 拖放多个文件到程序窗口后，无法正常打开所有文件（3864，#88）
- 修改文档旋转页面时没有考虑原始页面的旋转角度（3867，#47）
- 替换字体功能未列出为当前用户安装的字体（4002，#101）
- 文件尺寸的数值错误（4084）
- 导出带输出文本指令的信息文件存在内存漏洞（4084）
- 提取页面功能在某些场合下会生成错误的文件（4084）
- 提高导出图片功能对轻微格式错误的图片的兼容性（4084，#119）
- 字母形式的页码标签少了一位数值（4088，#122）
- 合并文件在读写文件列表时可能导致程序崩溃（4091，#124）
- 合并文件功能的易用性调整（4094，#123）
- 尝试复制识别失败页面文本时会导致程序崩溃（4105）
- 生成书签功能“添加字体筛选条件”对话框在信息文件没有包含字体信息时会导致程序崩溃（4105，#130 )
- 批量修改文件功能在不指定信息文件时出错（4106，#132）
- 编辑器不支持空白页码标签（4121，#138）
- 删除页面批注无法正常工作（4124，#139）
- 无法正常访问网络路径（4128，#144）
- 无法提取表单内图片（4142，#152）
- 添加不存在的文件到重命名文件列表会导致程序崩溃（4153）
- 合并文件功能自动旋转页面适应源图像尺寸选项无效（4153）
- 点击生成书签功能“忽略文本”表头会导致程序崩溃（4153）
- 提取页面功能保留书签的功能在勾选清理文档选项后会失效（4153，#156）

**Comment by iamvicliu** [comment]
从小众软件过来，感谢作者

**Comment by miaomiaosoft** [comment]
虽从未用过此工具，但想说一句“好人应一生平安”

**Comment by yy981420974** [comment]
大佬厉害，有空学习一下

**Comment by pengwen135** [comment]
发布包推荐放Releases里面

**Comment by wmjordan** [comment]
> 发布包推荐放Releases里面

目前还在测试呢

**Comment by calcitem** [comment]
如果是测试版的话可以勾选 Pre-Rlease 复选框。

**Comment by qux-bbb** [comment]
> 如果是测试版的话可以勾选 Pre-Rlease 复选框。

或者Beta版本什么的，这样也许大家更清楚，下载使用测试的人也会多一些吧

**Comment by DoveBoy** [comment]
这可比放在网盘下载方便多了，期待以后放releases

**Comment by SadPencil** [comment]
推荐放Releases，这样有些镜像站可以对此进行自动同步，例如
https://github.com/SDU-Mirrors/wonderful-github-releases

**Comment by wmjordan** [comment]
准备发布正式版了，请大家下载最新的测试版看看有没有什么未发现的问题

**Comment by amumuamumua** [comment]
感谢大佬

**Comment by wmjordan** [comment]
新测试版 3979 修复了 #96 的问题

**Comment by wmjordan** [comment]
新的测试版修复了 3979 “编辑器”按钮失效的问题。

**Comment by ifliy233** [comment]
感谢大佬！！

**Comment by wmjordan** [comment]
github 在 issue 里不支持上传 7z 文件，在 release 里则可以上传任意文件。

**Comment by wmjordan** [comment]
是的，我这里网速慢，有时还上不来。手工把 7z 改个名字都比上传个 zip 快。
