### ISSUE TITLE
合并文档自动生成目录

### ISSUE THREAD

**Issue by hou6807628** [wmjordan/PDFPatcher#200]
我希望在合并pdf文件的时候，可以按照文件名称自动生成目录文件，并将目录插在合并文件的第一页。
这个功能可以实现吗？感谢！

**Comment by lforlgg** [comment]
这种应该属于专业的pdf软件范畴，查下foxit福昕高级PDF编辑器，金山pdf、adobe acrobat之类...

**Comment by wmjordan** [comment]
@lforlgg 
没有。
楼主需要的功能是生成至少一页的独立页面来放置目录，而不是导航用的书签。
由于我在有导航书签的时候从来不使用这种“目录”，所以暂时不会考虑花时间在上面。
