### ISSUE TITLE
能否支持设定每次打开补丁丁，视图都固定为缩放：“适合页面”页面布局：“单页”翻页

### ISSUE THREAD

**Issue by lforlgg** [wmjordan/PDFPatcher#204]
每次打开一个新的pdf文件的时候
希望：
❤**视图能记住上次关闭补丁丁时的设定状态**或者提供自定义设定：视图都固定为缩放：“适合页面”页面布局：“单页”翻页。
![moren](https://github.com/wmjordan/PDFPatcher/assets/105794681/5b291473-4252-4706-9b8c-ab145901b04f)

❤第一次往无书签pdf文件粘贴上已经编好的txt，在丁丁里变成书签后，此时书签视图**默认展开全部书签**为佳。
    每次粘贴完，下一步动作，全部展开来查看，几乎是必然要做的动作。
    默认展开全部书签。这样更有利于效果一目了然，看清楚哪些条目缺失页码。默认折叠的话，偶尔忘记全展开检查就以为下面的二级三级都是好的。实践中，有数次忘记全展开看看。

![moren2_ziped](https://github.com/wmjordan/PDFPatcher/assets/105794681/ca1ef0fd-7d1f-495c-bd56-95bf93935ad9)

多谢！❤

**Comment by hellosz123** [comment]
全部展开书签可能是会方便一点，或者要是能提供个设置选项也可以。期待大佬更新。辛苦了！

**Comment by wmjordan** [comment]
请下载新的版本，增加了记住缩放比例的行为。

**Comment by wmjordan** [comment]
> 第一次往无书签pdf文件粘贴上已经编好的txt，在丁丁里变成书签后，此时书签视图**默认展开全部书签**为佳

我认为不佳。

这是粘贴的书签格式错误所导致的，要掌握编辑技巧。


> **视图能记住上次关闭补丁丁时的设定状态**或者提供自定义设定：视图都固定为缩放：“适合页面”页面布局：“单页”翻页

相同的需求不要重复提。

**Comment by wmjordan** [comment]
> 第一次往无书签pdf文件粘贴上已经编好的txt，在丁丁里变成书签后，此时书签视图**默认展开全部书签**为佳

我认为不佳。

这是粘贴的书签格式错误所导致的，要掌握编辑技巧。


> **视图能记住上次关闭补丁丁时的设定状态**或者提供自定义设定：视图都固定为缩放：“适合页面”页面布局：“单页”翻页

相同的需求不要重复提。

**Comment by lforlgg** [comment]
> > 第一次往无书签pdf文件粘贴上已经编好的txt，在丁丁里变成书签后，此时书签视图**默认展开全部书签**为佳
> 
> 我认为不佳。
> 
> 这是粘贴的书签格式错误所导致的，要掌握编辑技巧。
> 
> > **视图能记住上次关闭补丁丁时的设定状态**或者提供自定义设定：视图都固定为缩放：“适合页面”页面布局：“单页”翻页
> 
> 相同的需求不要重复提。

1.0.2.4311新版很好用。那个+-号用的妙。多谢，辛苦了！
