### ISSUE TITLE
程序在未选中“允许导出隐藏图片”时导出了裁剪框以外的图片

### ISSUE THREAD

**Issue by Charltsing** [wmjordan/PDFPatcher#217]
[看不见的图.zip](https://github.com/user-attachments/files/16200950/default.zip)

用PDFPatcher会导出三个图片，有两个是图片扫描王的logo。没有勾选允许导出隐藏图片。
用其它pdf工具打开看不到这两个图片，Acrobat也看不到

怎么识别这两个多余的图片呢？

![1](https://github.com/user-attachments/assets/491d68df-a141-4a27-9f9d-2fdb161c0761)

**Comment by wmjordan** [comment]
是程序的缺陷。页面的裁剪框已经排除了这两张图片，不应导出。如果将裁剪框拉大，就会发现这两张图处于正文图片右下角。
![image](https://github.com/user-attachments/assets/529299e4-339e-4aa8-8ba1-689682cb7f0a)

**Comment by Charltsing** [comment]
文档结构探查器能看到图片的位置信息吗？

**Comment by wmjordan** [comment]
能看到。在输出对象指令（Do）前会有个矩阵（cm）指令，其参数最后的两个值，一般就是偏移位置。

**Comment by Charltsing** [comment]
> 能看到。在输出对象指令（Do）前会有个矩阵（cm）指令，其参数最后的两个值，一般就是偏移位置。

![33](https://github.com/user-attachments/assets/447d1731-aa35-4814-9c4f-0201a1668070)

如何删除这两个输出对象指令呢？

**Comment by wmjordan** [comment]
暂时没有办法。
