### ISSUE TITLE
mac m1 用户请求支持

### ISSUE THREAD

**Issue by qizidog** [wmjordan/PDFPatcher#22]
**使用场景**
mac m1 用户请求支持

**功能应该怎样实现**
保持与win操作一致

**类似软件**
mac平台下完全没有同类产品可供使用，反倒是win平台下已经有有类似的软件PdgCntEditor.exe了，mac用户只能通过虚拟机访问。

**其它内容**
与本需求相关的其它内容

**Comment by wmjordan** [comment]
幸福的楼主啊，我还没有 mac 机

**Comment by qizidog** [comment]
笑死😆 看来只能以后自己努力了

**Comment by calcitem** [comment]
我原以为在macOS下通过Visual Studio重新编译一下就可以发布macOS版。
