### ISSUE TITLE
发现源代码中的失误

### ISSUE THREAD

**Issue by Lenux92** [wmjordan/PDFPatcher#223]
**请简要描述你遇到的问题**
<img width="987" alt="image" src="https://github.com/user-attachments/assets/1ee20d31-690c-4e3d-b43b-8611ba6ce990">
使用命名空间``MuPdfSharp``该的``NewString``方法时缺少入参，如下
<img width="723" alt="image" src="https://github.com/user-attachments/assets/34323dcc-00d1-4878-bb5b-ea2193166e61">

**Comment by wmjordan** [comment]
这代码实际上没有用上，可删掉。

我正在改造 MuPDF 的动态链接库，考虑将所有功能迁移到 MuPDF，弃用 iText。
这个问题会随着新版本的 MuPDF 库而得到解决。

**Comment by Lenux92** [comment]
> 这代码实际上没有用上，可删掉。
> 
> 我正在改造 MuPDF 的动态链接库，考虑将所有功能迁移到 MuPDF，弃用 iText。 这个问题会随着新版本的 MuPDF 库而得到解决。

好的，感谢您的回复🤓

**Comment by Lenux92** [comment]
好的，感谢您的回复🤓
