### ISSUE TITLE
[bug]ctrl+w赋值给书签的页码，比真实pdf文件页码少1

### ISSUE THREAD

**Issue by retsyo** [wmjordan/PDFPatcher#225]
使用的是 1.0.3.4370 版本

在左侧的书签里面，随便选一个；然后，在右边的pdf浏览界面翻到某一页，例如它是PDF的第 $N$ 页，此时按 `ctrl+w`，可以看到左侧所选书签的页码，变成了 $N-1$ 。这里，应该是 $N$ 吧？

**Comment by wmjordan** [comment]
无法重现你提到的问题。
请留意阅读器上是否留有N－1页的底部，以及阅读器上方的页码框显示。
