### ISSUE TITLE
关于1.0.3.4411（9月1日）新版本变化的几点讨论。和对显亮列后的，点击单元格区域响应的建议。

### ISSUE THREAD

**Issue by lforlgg** [wmjordan/PDFPatcher#229]
在大多数时候，编辑改动了一个条目的页码后，都想观察下定位效果是否已经准确、是否符合预期。

如果一改动（失去鼠标焦点），就跳下往一个条目。反而麻烦（又要回头找那个项目点击）。
如果的确有人要加，可以以提供可选项形式，来符合他这种操作习惯。

目前PDFPatcher.1.0.3.4411（2024/9/1）这个方式反而非常不便。

大多时候不会在这里逐页填写书签页码（效率极低）。

🙏🏼感谢大佬。斟酌💖

**Comment by wmjordan** [comment]
有道理。
准备把它改回来。

下个版本优化一下，更改过页码之后，突出显示当前书签为选中项。这时，按空格键可以代替鼠标点击该项，快速检查是否定位正确。如需编辑下一项，可按↓光标键，转到下一项，再按P键，可使页码框进入编辑状态。

**Comment by lforlgg** [comment]
辛苦大佬。顺便关注：
✅“选中项的样式”改变行的显亮方式以后，有个变化没同步：
   原来需要点击书签的文本才会显示页面。现在应改为：点击文本所在单元格就显示页面。否则用户会困惑，明明这行是当前行，怎么页面内容没反应（不对应）。殊不知要点击文本才会真正定位到本条书签。

**Comment by wmjordan** [comment]
请到下载空间下载新的测试版。

**Comment by wmjordan** [comment]
> > 下个版本优化一下，更改过页码之后，突出显示当前书签为选中项。这时，按空格键可以代替鼠标点击该项，快速检查是否定位正确。
> 
> 自动刷新比按空格如何？ 感觉F5比空格更符合Windows日常习惯，学习成本更低。不过F5距离的远。不好按。有点难以取舍。

这不存在“刷新”的问题，文档没有改变，用空格就是相当于用鼠标点一下那书签。

> 
> 辛苦大佬。 顺便关注这个： ✅“选中项的样式”改变行的显亮方式以后，有个变化没同步： 原来需要点击书签的文本才会显示页面。现在应改为：点击文本所在单元格就显示页面。否则用户会困惑，明明这行是当前行，怎么页面内容没反应（不对应）。殊不知要点击文本才会真正定位到本条书签。

是特意设计成这个样子的，方便框选多个书签。
新的版本更改了界面反馈，当鼠标移到书签文本上会变成手形光标，表示可点击跳转。

> 
> ![test_ziped](https://private-user-images.githubusercontent.com/105794681/363457529-741b90eb-d2fb-4330-9d9b-b5c7372c56c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTMyMjcsIm5iZiI6MTcyNTYxMjkyNywicGF0aCI6Ii8xMDU3OTQ2ODEvMzYzNDU3NTI5LTc0MWI5MGViLWQyZmItNDMzMC05ZDliLWI1YzczNzJjNTZjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwODU1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzhmNzVjYzA4MjdiMWI1M2VjYmYyMmM5Y2M4Yjk1MGZlYjI1ZmUyYjVkZGYzZTY1M2Q4NzJjODUzNGM3MjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZB1QFHPRhSlFiBt7gbc7H5ohTmNhDjW6vZksBD7dxs0)
> 
> ✅关于“已经修改，提示保存”的对话框，原来目前陈述，容易陷入否定之否定绕脑子逻辑，建议考虑： ![saveTips_ziped](https://private-user-images.githubusercontent.com/105794681/363460283-0f0f9ba3-1574-4dd1-ac2e-d955fc595bab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTMyMjcsIm5iZiI6MTcyNTYxMjkyNywicGF0aCI6Ii8xMDU3OTQ2ODEvMzYzNDYwMjgzLTBmMGY5YmEzLTE1NzQtNGRkMS1hYzJlLWQ5NTVmYzU5NWJhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwODU1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTFlODFjOTQxNzE0NDg2MjYwMzI4ZjMwODRlYjRmOGJlMWU3NGE2MmZmNTZiMDdkMGQ4YTU2YjdjMTJiYjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4ek9ZqMjyHiu0kwt3j04R5SE3bPGClUUOSZwdUtZ8mU)

习惯成自然就好了。
新版本更改了对话框文本的陈述。要改按钮的话，要费些工夫，就先不在这里耗时间了。

**Comment by Charltsing** [comment]
> 请到下载空间下载新的测试版。

下载空间在什么地方?

**Comment by lforlgg** [comment]
> 习惯成自然就好了。 新版本更改了对话框文本的陈述。要改按钮的话，要费些工夫，就先不在这里耗时间了。

谢谢大佬，最新版本，我在猛烈使用了...我很习惯。主要是想照顾新接触的人杀我上手效率。
