### ISSUE TITLE
发现提取图片功能的bug，提取图片后的文件名排序不对

### ISSUE THREAD

**Issue by luojineng** [wmjordan/PDFPatcher#231]
部分pdf文件内估计有很多冗余图片，文件巨大，使用图片提取的文件名都是0001，0001[2]，0001[3]，0001[4] 而且内容顺序错乱的。。

**Comment by luojineng** [comment]
使用其他软件对pdf清理优化以后再提取图片 才没有出现上面说的情况。

**Comment by wmjordan** [comment]
在用的是什么版本？
导出时的选项是什么？你试过里面的选项组合了吗？
