### ISSUE TITLE
补丁丁目前这个保存的过程，感觉可以再改进到更简明直接些（附想象图）

### ISSUE THREAD

**Issue by lforlgg** [wmjordan/PDFPatcher#232]
Acrobat、福昕PDF之类的工具，修改完书签后，点一下保存按钮，大概1-3秒，没什么明显的等待感觉，就轻松保存好了。
补丁丁要用几十秒完成整个保存过程，感觉可以改进一下。或者可以分开来：
✅常用的“直接保存”，比如只是附加了书签这种操作，一点即存，简单明了，几秒内完成。
✅修改了pdf结构的，需要优化的，点“优化保存”沿用原来的。

目前补丁丁的保存流程比较复杂，操作时间长，工作效率偏低。
已经打钩（需主动操作）确认覆盖原文件了。又弹一个窗确认一次“覆盖”，有二次重复之嫌。

看到他保存，对于部分文件，需要较长时间才走完进度条，很多时候点好保存按钮确定后，趁保存进度的时间。我就去别的程序窗体忙点其他工作。
但有时候这保存界面跑别的窗体后面去了，被遮住了，也就注意不到它。

等我从别的程序忙完回过神来，原来保存还没进行下去，窗口还等我再确定一次。😁
这种困扰出现次数不少。如果光盯着它等它完成保存进度，几秒到几十秒不等，实在有点久。

目前流程：
①原界面，点保存
②弹出对话框“设置”覆盖，点确定。
*③弹出对话框“确认”覆盖，点确定。
*④弹出对话框“流程”，点取消或返回。
⑤回到原界面。

![save](https://github.com/user-attachments/assets/25c38cfb-f531-4dd4-854c-e0c4aec31b28)

建议可以简化掉两个弹窗界面：
①原界面，点保存按钮。（如果想有其他设定，点“优化保存”按钮——使用概率低）
②弹出对话框确定“覆盖”，点确定。
③原界面，在下方显示保存过程。同时禁止其他区域的菜单、按钮、滚动条操作，直到保存进度条走完，直接界面恢复原状。

![save_ziped](https://github.com/user-attachments/assets/5856d25c-0569-426b-a45f-f33b6b6bcb68)

🙏🏼感谢！

**Comment by hellosz123** [comment]
保存这个操作默认直接覆盖可能是会更方便一点。
弹出“确认”覆盖的对话框不在最前端的问题有时候是会出现。
希望大佬有空了考虑一下。辛苦了！

**Comment by wmjordan** [comment]
请下载新的测试版。

**Comment by lforlgg** [comment]
> 请下载新的测试版。

感谢感谢，辛苦了！好用！
