### ISSUE TITLE
请为文档结构探查器为表单和批注等显示其内容流的命令节点

### ISSUE THREAD

**Issue by Charltsing** [wmjordan/PDFPatcher#233]
[0004.zip](https://github.com/user-attachments/files/17074489/0004.zip)
![捕获](https://github.com/user-attachments/assets/e051b898-139b-4069-8fe2-25ee1095fc22)

我用pdfbox的debugger可以看到Fm0中的Tj内容，补丁丁找不到

另外我发现文档结构查看器有的内容可以复制，有的不行。例如 Tj 中的数据无法复制

**Comment by wmjordan** [comment]
表单里的指令暂时没有解析。
你选中上图的“Fm0”后，点击“查看”按钮，就能看到表单内的指令。

**Comment by Charltsing** [comment]
> 表单里的指令暂时没有解析。 你选中上图的“Fm0”后，点击“查看”按钮，就能看到表单内的指令。

 可以考虑在点击节点之后，在下面的那个帮助窗口里面显示解析内容。

**Comment by Charltsing** [comment]
[23.zip](https://github.com/user-attachments/files/17081784/23.zip)
![3](https://github.com/user-attachments/assets/90631b3f-3c0b-49fc-b4d5-34cf36163c0b)

Contents不全是可见字符，遇到不可见字符例如00，查看的信息就可能截断。

**Comment by wmjordan** [comment]
遇到这种情况，可以用“导出”按钮，把内容导出成文件。

**Comment by Charltsing** [comment]
> 遇到这种情况，可以用“导出”按钮，把内容导出成文件。

二进制文件没法直接看，也许可以把00替换成.再输出文本

**Comment by wmjordan** [comment]
不会考虑替换。
导出成文件后，可以用支持 NUL 字符的文本编辑器或十六进制编辑器查看。

也许后面会为表单等内容解析指令，和页面类似，生成一个“命令”节点。

**Comment by Charltsing** [comment]
能生成命令节点也不错，只是不知道要等到哪一年。

其实Contents里面的00字节都在Tj中，转成.也不影响查看结构细节。

我目前的处理办法是检查Tj是不是含有不可显示字符，如果有的话，把Tj中的内容按16进制输出，然后做个标记，能看明白就行。
这样不需要其它第三方软件。

毕竟保存再看实在太慢了。

**Comment by wmjordan** [comment]
请下载新的测试版本。

![image](https://github.com/user-attachments/assets/174844e9-9745-476c-abca-1a5849ca2b36)

**Comment by Charltsing** [comment]
[测试不通过.zip](https://github.com/user-attachments/files/17150142/default.zip)

一个被截断，一个乱码，具体看压缩包

**Comment by wmjordan** [comment]
> 能生成命令节点也不错，只是不知道要等到哪一年。

已经说过不考虑替换\0了。前面的帖子给了你截图，一个星期都没够就做出来了。

**Comment by wmjordan** [comment]
刚刚上传了一个新的测试版。
除了替换了部分不可见字符为八进制表示形式之外，还增加了切换显示编码的功能。

**Comment by Charltsing** [comment]
我不太清楚为什么你要采用八进制显示的方式。我是希望看到原始byte字节的，这样方便后继处理。

B8FC.pdf显示正常了。

**Comment by Charltsing** [comment]
[Artifact-Contents.zip](https://github.com/user-attachments/files/17165207/Artifact-Contents.zip)
![乱码](https://github.com/user-attachments/assets/db9e9fc1-704a-4bf4-8092-c84efddbc5d2)

Artifact-Contents 显示乱码。

**Comment by wmjordan** [comment]
PDF规范里支持的转义就是8进制。

如果你关心的是Tj里的文本内容，你应该看展开的命令节点，里面已经给你做好了解码的工作，并且给出了参数的十六进制表示形式。

**Comment by wmjordan** [comment]
内容流不一定都是用ASCII、GBK或统一码编码的。
PDF补丁丁的源码都是开放的，你可以看看它是怎样解码文本的。

别想什么用正则表达式直接匹配TJ或Tj内容来筛选文本，那是歪路。遇到CID字库就马上抓瞎。

**Comment by Charltsing** [comment]
> 内容流不一定都是用ASCII、GBK或统一码编码的。 PDF补丁丁的源码都是开放的，你可以看看它是怎样解码文本的。
> 
> 别想什么用正则表达式直接匹配TJ或Tj内容来筛选文本，那是歪路。遇到CID字库就马上抓瞎。

你可能没太理解我的应用场景。

我在写PDFCommander，这是个永久免费的[去水印工具](https://www.52pojie.cn/thread-1943717-1-1.html)，目前此软件真的可以实现万能去除水印。

通过PDFPatcher，我需要看Tj里面的文本，但有时候实际操作是替换16进制的原始字节。最终操作是针对原始字节进行的。

所以，我是希望PDFPatcher能看到Tj文本（看到文本的目的是为了定位原始字节），同时又能把文本显示为原始字节（某些pdf查找水印需要用原始字节），毕竟操作是针对后者进行的。

如果PDFPatcher只能看到文本，不能切换显示Tj里面的原始字节，我就得手工干活了。其实我无所谓，只是大部分软件用户没啥操作基础，找不到文本水印的位置和字节就没法写参数。

**Comment by wmjordan** [comment]
我知道你想做的工作。
之前已经有网友给我提过这个事情，所以我才将那个查看器给改了一下。
我一般都不使用这界面，而是直接看命令节点的输出结果。

你要做好这个筛选文本的工作，就必须知道怎么解码和重新编码文本。这是绕不过去的。否则，只会浪费你和我的时间。

**Comment by Charltsing** [comment]
> 我知道你想做的工作。 之前已经有网友给我提过这个事情，所以我才将那个查看器给改了一下。 我一般都不使用这界面，而是直接看命令节点的输出结果。
> 
> 你要做好这个筛选文本的工作，就必须知道怎么解码和重新编码文本。这是绕不过去的。否则，只会浪费你和我的时间。

你答复得比我编辑得都快。

我的意思是软件有分工，你的软件做水印肉眼识别，我的软件做水印处理。
毕竟PDFCommander是个命令行工具，没有界面，不像商业软件那样点选就能删软件。水印全靠肉眼识别，这就突显补丁丁的重要作用了。没有你这个软件，很多人连水印都找不到。

我不能在PDFCommander里面做解码文本，因为没有UI。而且，实际上不需要解码我就能处理水印。
但是，大部分菜鸟就不行了，得给他们一个找水印的软件。

**Comment by wmjordan** [comment]
如果是给普通用户用的话，那就更不能让他们看 Contents 了。

你应该知道 PDF 不是所有文本都是使用国标或统一码编码的，而且这种文档绝非少数。
得想点别的办法。

**Comment by Charltsing** [comment]
我见过的PDF中的Contents都是ascii编码的，只是Tj里面或者其它个别地方是乱七八糟的编码。PDFCommander所作的一部分工作就是把这些乱七八糟的文本原始字节找到，然后替换掉，达到去水印的目的。

如果你见过Contents内容是非ascii编码的，找找有没有样本让我看看。

我平时工作很少用pdf，不是专业搞pdf文档解析的。我只是临时写个工具救急。发到吾爱发现用途甚广，很多人需要它，所以才慢慢更新成现在这个万能工具。

**Comment by Charltsing** [comment]
PDFBox的Debugger有nice和raw两种查看模式，前者就是我要的混合模式，唯一的问题是我希望以16进制的字节码显示，而不是八进制。因为需要复制字节码。

![捕获](https://github.com/user-attachments/assets/f5dbb252-130e-4399-84a8-6e671d137681)

https://github.com/wmjordan/PDFPatcher/issues/233#issuecomment-2379346942

**Comment by wmjordan** [comment]
> Contents正常应该都是ASCII的吧，如果有其它编码的找找有没有样本让我看看。

显然不是。
这个就是一例：

[test.pdf](https://github.com/user-attachments/files/17177308/test.pdf)

**Comment by wmjordan** [comment]
更甚者如下。
[test.2.pdf](https://github.com/user-attachments/files/17177330/test.2.pdf)

**Comment by Charltsing** [comment]
> 更甚者如下。 [test.2.pdf](https://github.com/user-attachments/files/17177330/test.2.pdf)
![捕获](https://github.com/user-attachments/assets/5aea4702-9de3-4080-9203-65680455c5b4)

没太看懂你说的不是ASCII是啥意思。我看16进制 71 0A 31 36 2E 这就是ASCII啊

**Comment by wmjordan** [comment]
> 没太看懂你说的不是ASCII是啥意思。我看16进制 71 0A 31 36 2E 这就是ASCII啊

我上传的两个示例文件是针对这句话而言的：“你应该知道 PDF 不是所有文本都是使用国标或统一码编码的，而且这种文档绝非少数。”
内容流的指令是在 ASCII 字符集里，但是文本指令的参数不是。
不借助工具不可能在使用 CID 字库的 PDF 文件里看出文本指令输出了什么文本。

**Comment by Charltsing** [comment]
> > 没太看懂你说的不是ASCII是啥意思。我看16进制 71 0A 31 36 2E 这就是ASCII啊
> 
> 我上传的两个示例文件是针对这句话而言的：“你应该知道 PDF 不是所有文本都是使用国标或统一码编码的，而且这种文档绝非少数。” 内容流的指令是在 ASCII 字符集里，但是文本指令的参数不是。 不借助工具不可能在使用 CID 字库的 PDF 文件里看出文本指令输出了什么文本。

你说的对，现在PDFCommander缺乏文本指令参数的解码功能，导致查找文本水印相对困难。因为没有UI，所以我的软件不打算写文本解码功能。我觉得补丁丁可以弥补这个问题，给菜鸟们谋个福利。

谢谢你的卓越工作

**Comment by wmjordan** [comment]
让我花点时间想想怎样让普通用户可以相对轻松地指定要删除的内容。
下一个版本会更新 MuPDF 组件库，到时候看看是否有更好的办法。

**Comment by wmjordan** [comment]
去水印的需求在 #209 ，因内容与本帖提到的需求有重合之处，可到该处继续讨论。

**Comment by Charltsing** [comment]
仔细想了想，没有混合模式输出也没啥。把Contents导出之后，在文本编辑器里面把乱码转成16进制字节就行了。
