### ISSUE TITLE
字体内嵌后，字符宽度信息丢失

### ISSUE THREAD

**Issue by strnghrs** [wmjordan/PDFPatcher#234]
**请简要描述你遇到的问题**
[FontWidth.pdf](https://github.com/user-attachments/files/17075364/FontWidth.pdf)

**重现问题的步骤**
步骤如下：
1. 对附件中的PDF做字体内嵌，字体选黑体
2. 内嵌后字符明显超宽，都快超出页面范围了

**预期的结果或行为**
导出字体信息看了一下，内嵌后字体描述中的宽度信息全部丢了，只剩下一个DW 1000，所以超宽了。

**Comment by strnghrs** [comment]
[FontWidth2.pdf](https://github.com/user-attachments/files/17075876/FontWidth2.pdf)
这个PDF内嵌字体后也会出现宽度变化：内嵌字体时如果选择“同时删除文本尾随空格”，则字符就会挤在一起，否则不会

**Comment by wmjordan** [comment]
是特意把宽度信息删掉了。下个版本给个选项设置是否保留宽度信息。

**Comment by strnghrs** [comment]
查询Adobe出版的Technical Note #5079，FontWidth.pdf的FontDescriptor中W数组中7716 [ 250 ]的值250就是空格的宽度，7716是空格的CID值

**Comment by strnghrs** [comment]
我觉得还是不应该忽略W数组中的其他值，因为其中包含了字母、数字、符号的宽度。提交的示例PDF里只有中文，所以可能会误导你觉得没有其他W值也没事，但如果手工改一下显示内容，比如说显示宽度差距较大的i、W，可能会发现新的问题

**Comment by wmjordan** [comment]
是的，不应该忽略W里其它的值，但那个文档里，除了空格之外，W数组里其它的字符都没有使用到，没有用到的字符是不会嵌入到新的文档的，所以也无需保留。
我刚刚上传了一个新的版本（1.0.4.4467），用FontWidth和FontWidth2测试过，好像没什么问题。请找找页面中有连续一串英文或数字的文档，再测试看看。

**Comment by strnghrs** [comment]
cnblogs上只有4449的链接，没有4467的

**Comment by wmjordan** [comment]
刚刚更新主页了。

**Comment by strnghrs** [comment]
[FontWidth.pdf](https://github.com/user-attachments/files/17145864/FontWidth.pdf)
[5079.Adobe-GB1-5.pdf](https://github.com/user-attachments/files/17145865/5079.Adobe-GB1-5.pdf)
用26个大写字母试了一下，嵌入以后W完全没有了，所以显示仍然超宽，见附件中的PDF。
如果想测试其他字母、数字、符号，用UltraEdit32打开附件的PDF文件，按CTrl+H键进入十六进制模式，搜索、定位到ASCII串6 0 obj，手工覆盖Tj前面的字符串，即可更改显示内容。
这个PDF中的W数组定义了CID编码814～907的宽度，为了便于对应编码和字符，把Technical Note #5079也给你传一份。

**Comment by wmjordan** [comment]
GBK-EUC-H 这个表里有两组映射到这些CID编码范围。

第一组是
````
<21> <7e> 814
````

第二组是
````
<aaa1> <aafe> 814
````

程序把814到940的范围都映射到后面那个范围去，所以就全丢掉了。为什么会有第二组映射呢？

**Comment by strnghrs** [comment]
第一组是半角符号的ASCII码，第二组你看一下是不是A3A1~A3FE，如果是，就是全角符号的GB码

**Comment by wmjordan** [comment]
第二组不是A3A1~A3FE，是aaa1到aafe，对应一组越南文字，真是奇怪。

参见 Adobe 的 cmap 文件：
https://github.com/adobe-type-tools/cmap-resources/blob/f5cf3bca7fdfeaceb77aa82847e974f2306c20b4/Adobe-GB1-6/CMap/GBK-EUC-H#L1377

**Comment by strnghrs** [comment]
GBK编码，就不要管越南文字了

**Comment by wmjordan** [comment]
嗯，不纠结那么多，先手工把它们覆盖掉吧。
虽然可以保留W的值，但由于替换过的字体宽度可能与原字体不一致，效果不一定理想的。

<img width="206" src="https://github.com/user-attachments/assets/0ce41e41-8f86-484e-a05a-e02bbb95e1f4">

替换后变成这样：
<img width="206" alt="image" src="https://github.com/user-attachments/assets/129fe05e-ccc6-48ea-bae9-f84e7566bf80">

**Comment by wmjordan** [comment]
由于我电脑上没有“方正宋黑简体”，程序自动用默认字体替代了文档缺失的字体。替换时使用的是“方正宋黑体_GB18030”

**Comment by wmjordan** [comment]
已经将新的测试版上传到网盘了。请测试看看。

**Comment by strnghrs** [comment]
没有就对了，真装了那个字体反而会显示乱码。测试前可以手工修改原始PDF的字体名，比如说改成宋体

**Comment by strnghrs** [comment]
[FontWidth.pdf](https://github.com/user-attachments/files/17158722/FontWidth.pdf)
字母、数字测试已经没有问题，符号测试还有点问题，见附件PDF

**Comment by wmjordan** [comment]
上一个版本有个地方逻辑不妥当。
已经将新的测试版上传到网盘了。请再测试看看。

**Comment by wmjordan** [comment]
请下载4501测试版，4495处理竖排字库有问题。

**Comment by strnghrs** [comment]
其他所有字母、数字、符号都试过了并且没有问题，只有唯一一个符号不知道算不算问题：
附件PDF中的半角美元符号，在Acrobat下显示为人民币符号，用补丁丁内嵌字体后显示为半角美元符号。
如果用Foxit，则都显示为半角美元符号。
[FontWidth.pdf](https://github.com/user-attachments/files/17186032/FontWidth.pdf)

**Comment by wmjordan** [comment]
应该不是问题吧。

补丁丁的阅读器有一个机制，在遇到未嵌入字库时，会自动扫描系统里的字库，看看有没有刚好和所缺字库同名的，如果有，就会用该字库来显示。
对于“黑体”字库，在GBK-EUC-H下，“$”应该还是“$”才对，没有什么理由要转换为“￥”。
