### ISSUE TITLE
保存PDF文件，有损压缩把输出的pdf变为全黑，无论参数怎么调。

### ISSUE THREAD

**Issue by C-INIT** [wmjordan/PDFPatcher#235]
**PDF补丁丁的版本**
1.0.3.4411

**请简要描述你遇到的问题**
保存PDF文件->压缩->尽量将黑白图片转成黑白，这项勾选后，无论门限值怎么调，或者改为“抖动图像”，输出的pdf页面均为黑色。
![image](https://github.com/user-attachments/assets/0c4a53ce-4f15-4b9e-b1f6-395782f925fa)

**重现问题的步骤**
步骤如下：
1. 使用如下附件（原书测试样例，10页）：
[柯林斯英语语法丛书-易混淆词 (卡彭特)[2].pdf](https://github.com/user-attachments/files/17172222/-.2.pdf)

2. 保存PDF文件选项如下：
![image](https://github.com/user-attachments/assets/6902c27b-c959-4e84-bbdf-76713efd4209)
![image](https://github.com/user-attachments/assets/b4d20038-523a-4db4-8e84-a695bdd2acbb)
![image](https://github.com/user-attachments/assets/d753b482-6778-47db-8dd1-b142d4aef8a2)
![image](https://github.com/user-attachments/assets/4d6995f4-e511-4c8a-bd9a-dffd866b9801)
![image](https://github.com/user-attachments/assets/7da56ad6-999c-4dcc-ac5f-4d50096f6c6e)
![image](https://github.com/user-attachments/assets/48d7bb0c-8e88-4fa6-bceb-53bd787f98fb)
![image](https://github.com/user-attachments/assets/73fc862c-e2aa-46ed-8807-bcd713696023)
![image](https://github.com/user-attachments/assets/3e65ce02-0793-4179-9abf-a240ae59561f)

3. 最终得到一个全黑的PDF文件：
![image](https://github.com/user-attachments/assets/cffc0694-2586-49d0-9ac4-0cb3147e28c1)

**补充**
“保存PDF文件->压缩->尽量将黑白图片转成黑白”这个功能对其他PDF文件能起作用。能把大多数灰度图像压缩为黑白图像，但仍无法识别部分灰度图像并将其正确转化，如下（左页转化成功，右页转化失败）：
![image](https://github.com/user-attachments/assets/9572dea9-f30a-410e-b2d5-0ca94b4ffd1e)

关于上面提供的附件“柯林斯英语语法丛书-易混淆词 (卡彭特)[2].pdf”，我曾把它每一页都导出为图像，再重新合成pdf，也是一样的问题。导出过程中，我勾选了“将黑白图片保存为TIFF文件”，但依旧保存为PNG文件。

推测该问题可能与程序无法正确识别灰度图像有关。

**Comment by wmjordan** [comment]
> 导出过程中，我勾选了“将黑白图片保存为TIFF文件”，但依旧保存为PNG文件

黑白图片是指只有黑色和白色（不包含灰色）的图片。示例文档中的图片是灰度图片，不是黑白图片，因此，要保存成PNG格式才能做到无损。

全黑图片的问题已经在刚刚上传的测试版中得到解决。请到网盘空间下载4504测试版。
