### ISSUE TITLE
增加图片替换功能

### ISSUE THREAD

**Issue by kaiceo** [wmjordan/PDFPatcher#3]
老版本的pdf文件内嵌图片通常包含CCITT、JPEG2000等非JPEG格式图片，能不能在合并文件或编辑保存的时候转换为JPEG
[t.pdf](https://github.com/wmjordan/PDFPatcher/files/7795251/t.pdf)

**Comment by wmjordan** [comment]
转成JPEG有什么好处呢？

**Comment by kaiceo** [comment]
在一个[pdf2htmlEX](https://github.com/pdf2htmlEX/pdf2htmlEX)（支持jpeg、png、svg ）的项目应用中，ccitt 这种非jpeg压缩会出现转换图片失败

**Comment by wmjordan** [comment]
建议您向他们提需求吧

**Comment by kaiceo** [comment]
已经提过了，但是这个分支还没给反馈
