### ISSUE TITLE
支持PDF文档打印功能

### ISSUE THREAD

**Issue by Glepooek** [wmjordan/PDFPatcher#31]
**使用场景**
很多场景，如最常见的办公场景。

**功能应该怎样实现**
加载PDF文档后，点击打印按钮，弹出打印设置页面，如下图所示：
![image](https://user-images.githubusercontent.com/10616673/148730292-3f911e6d-6cdc-42ed-af62-00b52a8038e7.png)
设置完毕后，点击打印按钮，打印机开始打印。

**类似软件**
WPS。如果做不到WPS这么强大的功能，希望能先实现选打印机、打印份数、打印页面范围等基础功能。

**其它内容**
可以做到打印预览。

**Comment by calcitem** [comment]
如果PDF查看器的功能 PDFPatcher 都要实现一遍的话，估计名称不能叫 Patcher 了，得改叫 YAA (Yet Another Acrobat) 。😂

**Comment by calcitem** [comment]
如能最终有一个开源 Acrobat 当然是非常乐见的，不过，想探讨的是，PDFPatcher 存在的高价值在于弥补PDF工具的不足，抓住了痛点。既然随便一个PDF查看器都拥有的基本功能，定位于功能拓展的PDFPatcher 有什么理由要实现呢？我是感觉投入产出不成正比。

**Comment by Glepooek** [comment]
> 如能最终有一个开源 Acrobat 当然是非常乐见的，不过，想探讨的是，PDFPatcher 存在的高价值在于弥补PDF工具的不足，抓住了痛点。既然随便一个PDF查看器都拥有的基本功能，定位于功能拓展的PDFPatcher 有什么理由要实现呢？我是感觉投入产出不成正比。
你是对实现打印功能这个想法，还是没有理解到位。跟你谈论这些毫无意义，毕竟你也不是作者！！

**Comment by Glepooek** [comment]
你是对实现打印功能这个想法，还是没有理解到位。跟你谈论这些毫无意义，毕竟你也不是作者！！

**Comment by runqinshiye** [comment]
pdf打印，可以参见项目中用来呈现网页的开源工程：https://github.com/dstrucl/HtmlRenderer-1.5.0.6-with-print-pages-support
