### ISSUE TITLE
批量“自动快速生成文档书签”

### ISSUE THREAD

**Issue by xchnotxzh** [wmjordan/PDFPatcher#32]
**使用场景**
课件中的多个文档，每个文档的标题格式一样，想要快速批量生成书签。
按照 [自动快速生成文档书签](https://www.cnblogs.com/pdfpatcher/p/8452025.html) 的方法，只能一个个文档重复操作。

**功能应该怎样实现**
[自动快速生成文档书签](https://www.cnblogs.com/pdfpatcher/p/8452025.html) 的批量化：

1. 选取要批量生成书签的一批文件或文件夹。
2. 针对其中一个文件，按标题配置书签层级规则，然后生成书签。
3. 保存时，能选择"批量应用该书签层级规则到所有文档"。
4. 覆盖后，所有的文档都生成相同层级规则的书签。

**类似软件**
无

**其它内容**
我不确定是否已经实现了该功能？
如果已经实现的话，请问教程在哪？
如果还没实现的话，这算一个改进需求。

**Comment by wmjordan** [comment]
如果生成PDF文档时的文本样式完全一样，是有可能做到批量生成书签的。

我先做一个功能，允许你保存“自动生成书签”功能中的筛选条件，打开另一个PDF文档时，可以把它重新读出来，试试是否能筛选生成书签。

**Comment by wmjordan** [comment]
请提供两三个文档给我看看

**Comment by xchnotxzh** [comment]
> 请提供两三个文档给我看看

https://web.engr.oregonstate.edu/~sinisa/courses/OSU/CS261/CS261_Textbook/Chapter01.pdf
https://web.engr.oregonstate.edu/~sinisa/courses/OSU/CS261/CS261_Textbook/Chapter02.pdf
https://web.engr.oregonstate.edu/~sinisa/courses/OSU/CS261/CS261_Textbook/Chapter03.pdf
以此类推

**Comment by wmjordan** [comment]
> 我先做一个功能，允许你保存“自动生成书签”功能中的筛选条件，打开另一个PDF文档时，可以把它重新读出来，试试是否能筛选生成书签。

请下载新的测试版，它增加了保存和读取自动生成书签配置的功能。
![image](https://user-images.githubusercontent.com/12182730/159612601-3af45f78-e7b9-4211-a587-942bd11f2bcc.png)

**Comment by xchnotxzh** [comment]
另外，目前这样还是手动一个个生成，我发现已有功能能做到类似效果，可以跳过保存步骤，就是直接把下个文件拉到书签栏。
![image](https://user-images.githubusercontent.com/59308951/159713127-0362eaf3-0479-4d9f-9f6c-1d62504f2b5f.png)

**Comment by wmjordan** [comment]
> PDF补丁丁里生成的书签显示是空白的

新的测试版修复了这个问题
