### ISSUE TITLE
将 jbig2dec 分离为独立进程

### ISSUE THREAD

**Issue by calcitem** [wmjordan/PDFPatcher#42]
**功能应该怎样实现**

主程序系统调用 jbig2 解码器。

对于编码器，没有改造的需求，为了统一，也可以修改。

参考资料：https://www.cnblogs.com/babycool/p/3570648.html

**当前进展**

正在进行中，包括以下内容：

- [x] 将jbig2还原为原始代码。
- [ ] 补充原始代码的getopt命令行处理模块的代码。
- [ ] 将jbig2dec修改为编译可执行程序。
- [ ] 在C#部分，通过系统调用的方式调用 jbig2dec。
- [ ] 修改为预编译的方式。

**Comment by wmjordan** [comment]
将它编译成独立的程序，对于本项目来说似乎没有什么好处

**Comment by calcitem** [comment]
涉及许可证问题，此前已沟通。

**Comment by calcitem** [comment]
后续再和您邮件详细沟通。

**Comment by calcitem** [comment]
应该没有问题，是我此前的理解有误。close。
