### ISSUE TITLE
PDF纵向页面无法旋转至横向

### ISSUE THREAD

**Issue by LoyaltyMu** [wmjordan/PDFPatcher#47]
单张PDF页面设置成所有pdf都转90度的话可以使用
如果是单独将纵向转换成横向无法成功，具体的设置如下：
![Uploading image.png…]()
[纵向.pdf](https://github.com/wmjordan/PDFPatcher/files/7874157/default.pdf)
附件是纵向的pdf  一直我明白该怎么弄    请教下老师 这个该咋设置

**Comment by wmjordan** [comment]
确认有这个问题。
旋转页面功能的页面方向筛选器没有考虑页面已存在的旋转角度。

**Comment by wmjordan** [comment]
请下载新的测试版。
