### ISSUE TITLE
无法点击识别图像文本按钮

### ISSUE THREAD

**Issue by killer1327** [wmjordan/PDFPatcher#48]
无法点击识别图像文本按钮

是因为Office 2019版本太高？

**Comment by calcitem** [comment]
参见 https://github.com/wmjordan/PDFPatcher/issues/17

**Comment by wmjordan** [comment]
嗯，这个问题暂时无法解决。

**Comment by wmjordan** [comment]
等实现了 #17 的功能之后，会重新实现识别图像文本的功能。
