### ISSUE TITLE
合并文件部分字体丢失

### ISSUE THREAD

**Issue by kaiceo** [wmjordan/PDFPatcher#63]
**合并早期pdf文件会出现字体丢失**

1. 使用如下附件 
[2005.zip](https://github.com/wmjordan/PDFPatcher/files/7912323/2005.zip)

2. 合并，使用默认合并选项
![QQ截图20220121181322](https://user-images.githubusercontent.com/63705580/150509263-a030829a-2f8f-4852-b667-27295172701b.png)

3. 字体丢失
![image](https://user-images.githubusercontent.com/63705580/150509449-d0761745-60b5-4917-a355-542b84a8e8fc.png)

**Comment by wmjordan** [comment]
怎么会这样的呢？
<img width="479" alt="image" src="https://user-images.githubusercontent.com/12182730/150521899-0e53f5c6-6941-4901-86c9-b1d1977ebf92.png">

**Comment by wmjordan** [comment]
[合并后的文档](https://github.com/wmjordan/PDFPatcher/files/7913047/2.pdf)

**Comment by kaiceo** [comment]
![image](https://user-images.githubusercontent.com/63705580/150522388-214ef048-62c5-44f2-b321-0a1cae984a0f.png)
请查看你合并后的文档第二个文档的书签位置

**Comment by kaiceo** [comment]
哪个排在第二个位置，哪个丢失字体，但是我不知道咋回事，这个是2005年的pdf，比较老

**Comment by wmjordan** [comment]
的确有这个问题。
要完美解决这个问题不太容易。
请先下载新的测试版看看。

**Comment by kaiceo** [comment]
用的是最新版的1.0.0.3786，也有这个问题

**Comment by wmjordan** [comment]
我刚刚上传了一个新的测试版。

**Comment by kaiceo** [comment]
![image](https://user-images.githubusercontent.com/63705580/150525981-ca340a82-ccd9-4afc-bd01-c2c009bfc823.png)
ok,我再测试一下， 你看看要不要在这里弄个发布版本的，好找

**Comment by wmjordan** [comment]
只是个小小修改，还是测试之中的，不想发 Release。

**Comment by kaiceo** [comment]
刚才简单测试了一下， 最新的3788版本没这个问题

**Comment by wmjordan** [comment]
程序原来的设计是力图尽量减小合并后文件的尺寸，但判断不同文件的数据是否重复冗余的方法有问题，导致数据丢失。现在我将原先的方法做成是可选的，在合并文件选项中增加了一个新的选项（默认不使用该算法，要勾选才会使用该算法）。
