### ISSUE TITLE
导出信息文件时扩展名多一个.字符

### ISSUE THREAD

**Issue by aimingoo** [wmjordan/PDFPatcher#70]
使用菜单【工具箱/导出导入信息文件】功能时，将自动在.pdf文件所在目录下生成.xml文件，但是生成扩展名会变成“..xml”。
在导入时不会识别这个多出来的字符，必须手工更名为“.xml”才行。

**Comment by wmjordan** [comment]
我重现不出您提到的问题。请详细描述一下操作步骤。

**Comment by aimingoo** [comment]
@wmjordan 重试了一下，知道问题出在哪儿了。

要点：列表里是多个文件。

在"PDF信息文件"那里，
  - 如果不是用“浏览...”在选择一个路径，而是手工填一个的话，就一定会出这个BUG。

并且（当列表中是多文件时）：
  - 如果用“浏览...”来选择，不是显示为“..../<源文件>.xml”，而是显示成第一个文件的.xml文件。
  - 如果用“浏览...”来选择，那么无论选择到哪个目录，生成的.xml文件总是在源文件所在目录下。
  - 如果用工填写的话，只要这里的路径是非空的（例如随便填个abc），那么程序就能运行通过，并且文件扩展名总是“..xml”。

**Comment by wmjordan** [comment]
好的，重现出您提到的问题了。请下载新的测试版，看看是否还有问题。

实际上，我已经很多年没用过这个功能了。

**Comment by aimingoo** [comment]
已经可用了 点赞+n

对手工填写路径名来说会有点不友好。测试过的结果是：
 - 这里应该填一个从盘符开始的完整文件名，在使用时文件名会被替换成列表中的名字。

如果使用相对文件名，则在源文件所在目录下创建目录；如果使用不带盘符的绝对路径（"/”开始）文件名，那么会失效（提示创建了文件，但什么也没发生）。如果使用的是一个不规范的文件名（例如"a\b\c"），那么可能会不太符合预期地创建出一级或多级目录。

不过无妨……总之能用了先。建议的话，正式版在这里可以像“输出 PDF 文件”那样使用带替代符的方式。

这个功能我是用来向新pdf文件导入书签的。比如旧版本有书签，但质量低，新版本高质量但没书签，那么成批导出导入一下，挺方便的。

**Comment by wmjordan** [comment]
可以透露一下，哪里有可供“成批”导入的、带有书签的 PDF 文档吗？
