### ISSUE TITLE
报个bug，使用合并文件功能，长书签命名合并后会导致丢失前缀字符

### ISSUE THREAD

**Issue by jiaoting** [wmjordan/PDFPatcher#71]
比如书签里是：2017-03-15_“文化匠人，打造青岛城市之眼”——暨青岛德国总督楼旧址博物馆社教品牌惠民活动
合并后，成了：-03-15_“文化匠人，打造青岛城市之眼”——暨青岛德国总督楼旧址博物馆社教品牌惠民活动

**Comment by wmjordan** [comment]
不是缺陷。
添加文件前，不要选择如下圈中的选项。
<img width="357" alt="image" src="https://user-images.githubusercontent.com/12182730/151157753-54254798-3c82-4025-8b3c-d9135b4bec81.png">

**Comment by jiaoting** [comment]
我取消了，还是不行



在 2022-01-26 19:46:29，"WMJ" ***@***.***> 写道：

不是缺陷。
添加文件前，不要选择如下圈中的选项。


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wmjordan** [comment]
请详细描述你的操作步骤

**Comment by jiaoting** [comment]
选择要合并的文件，设定里面取消勾选删除前面的数字，然后关闭设置窗口，合并，打开合并后文件会发现，还是会删除前面的字数



在 2022-01-27 14:09:51，"WMJ" ***@***.***> 写道：

请详细描述你的操作步骤

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wmjordan** [comment]
由于这个功能的限制，要先修改配置，再添加文件

**Comment by wmjordan** [comment]
添加了文件之后，书签名称会出现在列表第二栏。
你可以查看该项是否正确。如果不正确，可以自行修改。
