### ISSUE TITLE
1.0.0.3802版本无法合并JPEG文件（新引入的故障）

### ISSUE THREAD

**Issue by lelandyang** [wmjordan/PDFPatcher#78]
**请简要描述你遇到的问题**
1.0.0.3802版本无法合并JPEG文件，同一JPEG文件在1.0.0.3794版本正常合并。

**重现问题的步骤**
步骤如下：
1. 使用如下附件 '...'
[Koala.zip](https://github.com/wmjordan/PDFPatcher/files/7994798/Koala.zip)

2. 打开某功能 '....'
图片合并为PDF功能

3. 选中哪些选项，点击哪些按钮 '....'
略

4. 出现的问题
报错“Object reference not set to an instance of an object. The document has no pages.”

**预期的结果或行为**
在完成上面的操作步骤后，您觉得程序应该是怎样工作的。

**相关截图或文件**
![image](https://user-images.githubusercontent.com/10257460/152349912-8cd5d406-2f16-458a-bb83-dc82fb2253d5.png)

**其它**
与本问题相关的信息
经过测试，在1.0.0.3794版本测试正常，怀疑为修复Palette故障时引入。附上1.0.0.3794版本生成PDF：
[test.zip](https://github.com/wmjordan/PDFPatcher/files/7994824/test.zip)

**Comment by wmjordan** [comment]
请下载新的测试版。
