### ISSUE TITLE
打开不正常的PDF文件闪退

### ISSUE THREAD

**Issue by lelandyang** [wmjordan/PDFPatcher#79]
**请简要描述你遇到的问题**
PDFPatcher在打开不正常的PDF文件直接闪退。

**重现问题的步骤**
步骤如下：
1. 使用如下附件 '...'
[test.zip](https://github.com/wmjordan/PDFPatcher/files/7994862/test.zip)

2. 打开某功能 '....'
无需打开任何功能，只要PDF非法就会出现此问题。

3. 选中哪些选项，点击哪些按钮 '....'

4. 出现的问题
程序闪退

**预期的结果或行为**
类似于Acrobat Pro，并未闪退，而是弹出警告框，如下图：
![image](https://user-images.githubusercontent.com/10257460/152351802-e6a46768-9c38-4222-b86a-08361c0adf28.png)

**相关截图或文件**
如果有必要，请附上截图或文件（最好能附上程序的界面截图，以便了解你现在使用的版本和操作选项等）

**其它**
本问题存在于1.0.0.3802及以下版本。

**Comment by wmjordan** [comment]
请下载新的测试版。
