### ISSUE TITLE
自动生成书签，有的文件无法生成书签。

### ISSUE THREAD

**Issue by xchnotxzh** [wmjordan/PDFPatcher#83]
**请简要描述你遇到的问题**
按照 [自动快速生成文档书签](https://www.cnblogs.com/pdfpatcher/p/8452025.html) 的方法。
有些文件，无法生成书签，这些文件的文字是可复制的。

**重现问题的步骤**
步骤如下：
1. 使用如下附件 '[测试文件](https://cs162.org/static/lectures/1-1up.pdf)'
2. 按照 [自动快速生成文档书签](https://www.cnblogs.com/pdfpatcher/p/8452025.html) 的步骤，针对标题"Goals for Today"，尝试生成书签。
3. 左下角没有显示识别出"Goals for Today"，并且左边的书签栏为空。

**预期的结果或行为**

 左下角显示识别出"Goals for Today"，并且左边的书签栏生成"Goals for Today"。

**相关截图或文件**
![image](https://user-images.githubusercontent.com/59308951/156488740-a31f89ef-6623-4632-b001-a55274306de2.png)

**其它**
这些文件的文字是可复制的，为什么不能生成书签？

**Comment by wmjordan** [comment]
已经重现了该问题，并在内部修复，请等新测试版本发布

**Comment by wmjordan** [comment]
请下载新的测试版。

**Comment by xchnotxzh** [comment]
> 请下载新的测试版。

测试通过。
