### ISSUE TITLE
“自动快速生成文档书签” 跳到当前页开头

### ISSUE THREAD

**Issue by xchnotxzh** [wmjordan/PDFPatcher#87]
**使用场景**
我习惯连页阅读PDF文件。

有些文件，标题并不是在开头，而是靠近中间，但是标题之上是有信息的。
按照 [自动快速生成文档书签](https://www.cnblogs.com/pdfpatcher/p/8452025.html) 的方法，生成的书签位置即标题位置，不能立刻看到完整页面，得手动往上拉才能看到标题之上的信息。
![image](https://user-images.githubusercontent.com/59308951/159155777-df8b4801-f5e5-44ed-9afa-0eba5086aa49.png)

**功能应该怎样实现**
[自动快速生成文档书签](https://www.cnblogs.com/pdfpatcher/p/8452025.html) 增加“跳到当前页开头”选项，生成后不管标题在什么位置，点击书签后都导航到当前页开头。

**类似软件**
无

**其它内容**
无

**Comment by TroyDanielFZ** [comment]
导出为XML文件后，修改`上`对应的属性。如果你想居中的话，就把对应的数值均改成相同的。如果你想让结果跳到当页开头，则删除`上`对应的属性。
另一方法，使用PDFPatcher里的页面偏移功能，整体向上偏移半页即可。

**Comment by wmjordan** [comment]
居中的方式不太合适。
目前，建议按照 @TroyDanielFZ 介绍的方法，自行调整一下。
<img width="345" alt="image" src="https://user-images.githubusercontent.com/12182730/159156259-d6341d84-d88b-4bfb-8435-2a07cc91bf48.png">

后面可能会提供一个选项，在生成书签时可以调整偏移量。

**Comment by xchnotxzh** [comment]
> 

可能是我理解错居中的意思了，我想达到的效果是 @TroyDanielFZ 说的书签“跳到当页开头”。
”跳到当页开头“选项 应该比 “偏移”选项 更实用，因为
1.针对所有页面偏移很可能太合适大部分文档，因为并不是每页的标题在中间，往往是大标题才在中间，所以并不是每页都需要偏移。
2.对于大部分情况，点击书签跳到当页开头，是符合预期的。

所以，如果后期提供选项的话，请提供”跳到当页开头“选项。

**Comment by xchnotxzh** [comment]
> 居中的方式不太合适。 目前，建议按照 @TroyDanielFZ 介绍的方法，自行调整一下。 <img alt="image" width="345" src="https://user-images.githubusercontent.com/12182730/159156259-d6341d84-d88b-4bfb-8435-2a07cc91bf48.png">
> 
> 后面可能会提供一个选项，在生成书签时可以调整偏移量。

可能是我理解错居中的意思了，我想达到的效果是 @TroyDanielFZ 说的书签“跳到当页开头”。
”跳到当页开头“选项 应该比 “偏移”选项 更实用，因为
1.针对所有页面偏移很可能太合适大部分文档，因为并不是每页的标题在中间，往往是大标题才在中间，所以并不是每页都需要偏移。
2.对于大部分情况，点击书签跳到当页开头，是符合预期的。

所以，如果后期提供选项的话，请提供”跳到当页开头“选项。

**Comment by wmjordan** [comment]
嗯，有时候我也遇到这样的情况，希望某类标题定位到页首。请下载新的测试版。

**Comment by xchnotxzh** [comment]
> 嗯，有时候我也遇到这样的情况，希望某类标题定位到页首。请下载新的测试版。
> 
> <img alt="image" width="389" src="https://user-images.githubusercontent.com/12182730/159161185-5ecf08d4-b06f-486f-bd29-fb42979f355d.png">

测试通过，但设计上可能有问题：
1.如果用户习惯从页首开始看页面，通常希望全部标题都到页首，但现在得每个标题勾一下，这是不是应该属于全局选项（类似于“合并同字体尺寸的相邻标题”）？
2.到页首是不是更普遍的需求？如果是的话，应该是默认到页首，到标题位置才是选项。

**Comment by TroyDanielFZ** [comment]
我不喜欢到页首，到页首更适合于章标题。
如果是我来操作，可能更偏好使用精准位置生成书签后，利用PP的快速选择功能选择章标题（使用AHK等定义快捷键`Alt+1`,`Alt+2`等），然后使用清除纵坐标，保存即可。

**Comment by wmjordan** [comment]
我也不喜欢到页首，不会考虑做成全局的。

在书签编辑器里，也是点两下按钮的事情（Ctrl＋A，右键“清除横坐标”），不算很麻烦吧。

**Comment by TroyDanielFZ** [comment]
> 默认的实现是跳转到标题偏上一行的位置。经过大量的测试，这个默认配置是最舒适的。

Can't agree more.

**Comment by xchnotxzh** [comment]
ok
