### ISSUE TITLE
批量拖入文件会导致文件名和文件内容不一致

### ISSUE THREAD

**Issue by xchnotxzh** [wmjordan/PDFPatcher#88]
**请简要描述你遇到的问题**
将一批文件拖入PDF补丁丁，有时会文件名和文件内容不一致。
如果生成书签并保存，往往会报错。

**重现问题的步骤**
步骤如下：
1. 使用如下附件
[web.engr.oregonstate.edu/~sinisa/courses/OSU/CS261/CS261_Textbook/Chapter01.pdf](https://web.engr.oregonstate.edu/~sinisa/courses/OSU/CS261/CS261_Textbook/Chapter01.pdf)
[web.engr.oregonstate.edu/~sinisa/courses/OSU/CS261/CS261_Textbook/Chapter02.pdf](https://web.engr.oregonstate.edu/~sinisa/courses/OSU/CS261/CS261_Textbook/Chapter02.pdf)
[web.engr.oregonstate.edu/~sinisa/courses/OSU/CS261/CS261_Textbook/Chapter03.pdf](https://web.engr.oregonstate.edu/~sinisa/courses/OSU/CS261/CS261_Textbook/Chapter03.pdf)
2. 一并拖入PDF补丁丁，可以看到文件名和文件内容不一致。
3. 根据标题生成书签并报错。

**预期的结果或行为**

1.批量拖入文件名和文件内容一致。
2.生成书签正常。

**相关截图或文件**
![image](https://user-images.githubusercontent.com/59308951/159714935-b64fde8f-12bc-4f29-8d83-0a75e4cc1c36.png)
![image](https://user-images.githubusercontent.com/59308951/159714703-58b81b29-d722-4782-a427-aec96cdf795b.png)

**其它**
无

**Comment by wmjordan** [comment]
请下载新的测试版。

**Comment by xchnotxzh** [comment]
测试通过
