### ISSUE TITLE
Pdf知识树

### ISSUE THREAD

**Issue by Megadotzip** [wmjordan/PDFPatcher#9]
大佬，能把开发补丁丁所需的知识储备罗列一下吗？
初学者实在不懂，没搜索到有效的资源。

**Comment by wmjordan** [comment]
我博客上有文章提到你所需要的知识和开发组件啊。您看了吗？
[12年历史的 PDF 补丁丁，今天开放源代码了](https://www.cnblogs.com/pdfpatcher/p/15728955.html)

**Comment by wmjordan** [comment]
或可参见本项目 Readme.md 说明
