### ISSUE TITLE
转换页面为图片-闪退

### ISSUE THREAD

**Issue by kunlunlangzi** [wmjordan/PDFPatcher#90]
当转换页面分辨率设置为1200或者2400时软件闪退，其他分辨率时正常转换。
![image](https://user-images.githubusercontent.com/59104351/161201092-589c239e-4bf3-4ca3-b908-312ea2d9b654.png)
![image](https://user-images.githubusercontent.com/59104351/161201148-ba0e63e2-6a90-4e21-aecc-e2cb106c721a.png)
Windows版本
![image](https://user-images.githubusercontent.com/59104351/161201471-26c0bdb8-92fe-497c-86c1-3eb77685b0c7.png)
软件版本
![image](https://user-images.githubusercontent.com/59104351/161202189-dcc946c6-3509-489f-a2f5-e43a25a2901e.png)

**Comment by wmjordan** [comment]
可能是图片太大，程序可用的内存不够了

**Comment by kunlunlangzi** [comment]
> 可能是图片太大，程序可用的内存不够了

谢谢解答！

问题如果没有重现的话，那就可能是我电脑的问题。

查看了一下内存占用最高24%。

3M以下的pdf转没问题的，3M多的转到一半闪退，更大的8M、9M的点击转化图片按钮，直接退出。

**Comment by wmjordan** [comment]
请把样本文件发给我，详细分析一下

**Comment by wmjordan** [comment]
请把样本文件发给我详细分析一下

**Comment by kunlunlangzi** [comment]
> 请把样本文件发给我详细分析一下

发您邮箱了，请查收!

**Comment by wmjordan** [comment]
收到，果然是内存分配的问题。图片被拉伸得太大了，内存分配不过来。

**Comment by AlphatoBeta** [comment]
我也遇到了这种情况，300DPI都闪退。PDF页面大小：10956.05mm*1190.41mm 软件版本：博客置顶最新版1.0.0.4064

**Comment by wmjordan** [comment]
新的版本可以避免这个情况发生。
