### ISSUE TITLE
只有一页的pdf浏览新版本无滚动条

### ISSUE THREAD

**Issue by runqinshiye** [wmjordan/PDFPatcher#91]
旧版本正常：
![75933354129e94000a4e97fa164f2a3](https://user-images.githubusercontent.com/76540623/162611585-90710f69-4961-41b9-a58e-fe1c20fe95f8.png)

当前版本异常：
![756e81105911c266a7531d24dc851f7](https://user-images.githubusercontent.com/76540623/162611610-9b1c2040-a90c-47fc-b3cd-50cf14a4eeae.png)

**Comment by wmjordan** [comment]
请发一个文件给我测试一下

**Comment by runqinshiye** [comment]
[test.pdf](https://github.com/wmjordan/PDFPatcher/files/8461589/test.pdf)

![}D@QX}S@_XZRLA(H8U}PRV0](https://user-images.githubusercontent.com/76540623/162678870-b3a6f7f6-d113-4682-833d-a008249cdc74.png)


> 请发一个文件给我测试一下

**Comment by wmjordan** [comment]
请用程序“检查新的版本”下载最新的测试版再看看

**Comment by runqinshiye** [comment]
懂了，开源已经弃坑，国人难免，表示理解。

**Comment by wmjordan** [comment]
请再下载新的测试版 3922 看看

**Comment by wmjordan** [comment]
这个问题应该和两周前修改工具栏时所作的变更有关，可能是 .NET WinForms 组件的缺陷

**Comment by wmjordan** [comment]
已经修复了本问题，请下载最新的版本

**Comment by runqinshiye** [comment]
经过验证，问题解决，感谢您的关注。
![20220412102719](https://user-images.githubusercontent.com/76540623/162867164-45fdbe01-fe0b-4b26-bdf5-b37ff7212cd8.png)

**Comment by wmjordan** [comment]
> 懂了，开源已经弃坑，国人难免，表示理解。

没有弃坑哈。

这个地方在前段时间总是连接不了。国产的 gitee 又不太好使，否则早转那边去了。
