### ISSUE TITLE
FreeImage.dll is not copied to bin folder by default, FreeImage.dll 没有被拷贝到bin目录下

### ISSUE THREAD

**Issue by Dunkelicht** [wmjordan/PDFPatcher#95]
**请简要描述你遇到的问题**
默认编译未拷贝FreeImage.dll 顾导出图片时无法加载FreeImage.dll

**重现问题的步骤**
正常编译后,使用导出显示报错

**预期的结果或行为**
建议自动拷贝FreeImage.dll 到编译后的bin目录, 方便测试和应用

**相关截图或文件**
报错文本: 很容易复现的

---------------------------
PDF 补丁丁
---------------------------
在导出图片时遇到错误：
Unable to load DLL 'FreeImage': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
---------------------------
OK   
---------------------------

**其它**
与本问题相关的信息

再次感谢pdfpathcer和作者 做出像PDF Patcher一样稳定可靠的软件一直是我的梦想, 我正通过源代码尝试学习C# 尤其是多线程编程, PDFPatcher可以在导出等处理PDF过程中不会让winform卡顿 ,这个是在学习如何实现的地方, 如果能用简单几句话说明一下我将不胜感激,不想浪费作者的时间哈...

祝大家快乐幸福!

**Comment by wmjordan** [comment]
谢谢您的提醒。我已经上传了新的源代码以修复您提到的问题。

> PDFPatcher可以在导出等处理PDF过程中不会让winform卡顿

BackgroundWorker
