### ISSUE TITLE
更新到 1.0.0.3927 之后，提取图片、导出元数据等功能不再自动指定 PDF 文件

### ISSUE THREAD

**Issue by balthild** [wmjordan/PDFPatcher#96]
**使用场景**

提取图片、导出元数据等

**功能应该怎样实现**

以前的版本中，在当前 tab 是一个已打开的 PDF 时，点击工具栏的「提取图片」（如下图）后，

![image](https://user-images.githubusercontent.com/2662758/163923856-342fc7ea-cfd9-467a-88fd-be934573e8cb.png)

新打开的 tab 中，「原始 PDF 文件」栏将自动填充为对应的 PDF 文件（如下图）。

![image](https://user-images.githubusercontent.com/2662758/163923889-d17e7841-d8e9-45aa-ac6b-316ee7ef3a99.png)

「导入导出信息文件」也是类似（如下图）。

![image](https://user-images.githubusercontent.com/2662758/163923988-7e75cbe6-b5dd-49b6-8fb3-6c4786f3e58d.png)

但最近更新测试版之后，这个行为没有了，我必须再手动把这一栏再填写一次，不太方便。希望能把这个功能加回来。

![image](https://user-images.githubusercontent.com/2662758/163922852-8c102904-f061-4f01-8e68-dc272e74e31b.png)

**类似软件**

旧版 PDF 补丁丁

**其它内容**

无

**Comment by wmjordan** [comment]
感谢您的报告。我最近也发现了这个问题，忘记要将其修复了。
请下载新的测试版。

**Comment by balthild** [comment]
感谢

**Comment by balthild** [comment]
我刚才更新到 1.0.0.4200 后，这个问题又重新出现了

**Comment by balthild** [comment]
感谢！确认 4217 中已修复。
