### ISSUE TITLE
寻找安装包文件

### ISSUE THREAD

**Issue by tongchangD** [wmjordan/PDFPatcher#99]
您好，我仔细阅读了您的使用手册，可我未找到文章里所说的PDFPatcher.exe文件 ，文件列表里存在7az.exe,可我双击之后没有任何回应，请问是什么原因，本人windows10 系统。

**Comment by wmjordan** [comment]
请仔细阅读博客网站，上面就有下载连接。
本站置顶的Issue上也有测试版。

**Comment by wmjordan** [comment]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/12182730/166416659-9c6316f6-512c-4c5c-96eb-c60bc2db9180.png">
